// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, Singleton, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { ClientController } from "./client-controller";
import type { AcmeClient } from "acme-sdk";
export @Module class RoutesModule {
	@Singleton @Provides static clientController(client: AcmeClient): ClientController {
		return new ClientController(client);
	}
	@IntoSet @Provides static clientControllerGetPing(clientController: ClientController): RouteDefinition {
		return {
			method: "GET",
			path: "/client",
			handler: (req, res) => clientController.ping(req, res)
		};
	}
}
