// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { BadRequestError, SseStream, disconnectSignal } from "@anvil-di/bellows";
import { EventsController, JobParams } from "./events-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static eventsControllerGetProgress(eventsController: EventsController): RouteDefinition {
		return {
			method: "GET",
			path: "/events/progress/:jobId",
			handler: async (req, res) => {
				const _params = JobParams.safeParse(req.params);
				if (!_params.success) {
					throw new BadRequestError(_params.error.message);
				}
				await eventsController.progress(_params.data, new SseStream(res, disconnectSignal(req)), disconnectSignal(req));
			}
		};
	}
	@IntoSet @Provides static eventsControllerGetPing(eventsController: EventsController): RouteDefinition {
		return {
			method: "GET",
			path: "/events/ping",
			handler: (req, res) => {
				eventsController.ping(res);
			}
		};
	}
}
