// AUTO-GENERATED by anvil v0.0.3. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import { Handler } from "./handler";
import type { HttpRequest, HttpResponse } from "./http";
import { RequestComponent } from "./request-component";
import type { RequestContext } from "./request-context";
import { RequestModule } from "./request-module";
export class AnvilAppComponent extends AppComponent {
	requestComponent(req: HttpRequest, res: HttpResponse): RequestComponent {
		return new AnvilRequestComponent(this, req, res);
	}
	static create(): AppComponent {
		return new AnvilAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return AnvilAppComponent.create();
}
export class AnvilRequestComponent extends RequestComponent {
	constructor(private parent: AnvilAppComponent, private req: HttpRequest, private res: HttpResponse) {
		super();
	}
	private getHttpResponse(): HttpResponse {
		return this.res;
	}
	private getHttpRequest(): HttpRequest {
		return this.req;
	}
	private getRequestContext(): RequestContext {
		return RequestModule.context(this.getHttpRequest());
	}
	private getHandler(): Handler {
		return new Handler(this.getRequestContext(), this.getHttpResponse());
	}
	handler(): Handler {
		return this.getHandler();
	}
}
