// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { TodoControllerGetListData, TodoControllerGetListResponse, TodoControllerPostCreateData, TodoControllerPostCreateResponse, TodoControllerDeleteRemoveData, TodoControllerDeleteRemoveResponse, TodoControllerGetByIdData, TodoControllerGetByIdResponse, TodoControllerPutUpdateData, TodoControllerPutUpdateResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const todoControllerGetList = <ThrowOnError extends boolean = false>(options?: Options<TodoControllerGetListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<TodoControllerGetListResponse, unknown, ThrowOnError>({
        url: '/todos',
        ...options
    });
};

export const todoControllerPostCreate = <ThrowOnError extends boolean = false>(options: Options<TodoControllerPostCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<TodoControllerPostCreateResponse, unknown, ThrowOnError>({
        url: '/todos',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const todoControllerDeleteRemove = <ThrowOnError extends boolean = false>(options: Options<TodoControllerDeleteRemoveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<TodoControllerDeleteRemoveResponse, unknown, ThrowOnError>({
        url: '/todos/{id}',
        ...options
    });
};

export const todoControllerGetById = <ThrowOnError extends boolean = false>(options: Options<TodoControllerGetByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<TodoControllerGetByIdResponse, unknown, ThrowOnError>({
        url: '/todos/{id}',
        ...options
    });
};

export const todoControllerPutUpdate = <ThrowOnError extends boolean = false>(options: Options<TodoControllerPutUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<TodoControllerPutUpdateResponse, unknown, ThrowOnError>({
        url: '/todos/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};