// This file is auto-generated by @hey-api/openapi-ts

export type CreateTodoBody = {
    title: string;
};

export type TodoListSchema = {
    items: Array<{
        id: string;
        title: string;
        completed: boolean;
        createdAt: string;
    }>;
};

export type TodoQuery = {
    completed?: 'true' | 'false';
};

export type TodoSchema = {
    id: string;
    title: string;
    completed: boolean;
    createdAt: string;
};

export type UpdateTodoBody = {
    title?: string;
    completed?: boolean;
};

export type TodoControllerGetListData = {
    body?: never;
    path?: never;
    query?: {
        query?: TodoQuery;
    };
    url: '/todos';
};

export type TodoControllerGetListResponses = {
    /**
     * Success
     */
    200: TodoListSchema;
};

export type TodoControllerGetListResponse = TodoControllerGetListResponses[keyof TodoControllerGetListResponses];

export type TodoControllerPostCreateData = {
    body: CreateTodoBody;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodoControllerPostCreateResponses = {
    /**
     * Success
     */
    200: TodoSchema;
};

export type TodoControllerPostCreateResponse = TodoControllerPostCreateResponses[keyof TodoControllerPostCreateResponses];

export type TodoControllerDeleteRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerDeleteRemoveResponses = {
    /**
     * Success
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type TodoControllerDeleteRemoveResponse = TodoControllerDeleteRemoveResponses[keyof TodoControllerDeleteRemoveResponses];

export type TodoControllerGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerGetByIdResponses = {
    /**
     * Success
     */
    200: TodoSchema;
};

export type TodoControllerGetByIdResponse = TodoControllerGetByIdResponses[keyof TodoControllerGetByIdResponses];

export type TodoControllerPutUpdateData = {
    body: UpdateTodoBody;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerPutUpdateResponses = {
    /**
     * Success
     */
    200: TodoSchema;
};

export type TodoControllerPutUpdateResponse = TodoControllerPutUpdateResponses[keyof TodoControllerPutUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3002' | (string & {});
};