// This file is auto-generated by @hey-api/openapi-ts

export type Todo = {
    id: string;
    title: string;
    completed: boolean;
    createdAt: string;
};

export type TodoList = {
    items: Array<Todo>;
};

export type CreateTodoInput = {
    title: string;
};

export type UpdateTodoInput = {
    title?: string;
    completed?: boolean;
};

export type TodoControllerGetListData = {
    body?: never;
    path?: never;
    query?: {
        completed?: 'true' | 'false';
    };
    url: '/todos';
};

export type TodoControllerGetListResponses = {
    /**
     * Success
     */
    200: TodoList;
};

export type TodoControllerGetListResponse = TodoControllerGetListResponses[keyof TodoControllerGetListResponses];

export type TodoControllerPostCreateData = {
    body: CreateTodoInput;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodoControllerPostCreateResponses = {
    /**
     * Created
     */
    200: Todo;
};

export type TodoControllerPostCreateResponse = TodoControllerPostCreateResponses[keyof TodoControllerPostCreateResponses];

export type TodoControllerDeleteRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerDeleteRemoveErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type TodoControllerDeleteRemoveResponses = {
    /**
     * No Content
     */
    204: void;
};

export type TodoControllerDeleteRemoveResponse = TodoControllerDeleteRemoveResponses[keyof TodoControllerDeleteRemoveResponses];

export type TodoControllerGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerGetByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type TodoControllerGetByIdResponses = {
    /**
     * Success
     */
    200: Todo;
};

export type TodoControllerGetByIdResponse = TodoControllerGetByIdResponses[keyof TodoControllerGetByIdResponses];

export type TodoControllerPutUpdateData = {
    body: UpdateTodoInput;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodoControllerPutUpdateErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type TodoControllerPutUpdateResponses = {
    /**
     * Success
     */
    200: Todo;
};

export type TodoControllerPutUpdateResponse = TodoControllerPutUpdateResponses[keyof TodoControllerPutUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};