// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { PostController } from "./post-controller";
import { UserController } from "./user-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static postControllerGetList(postController: PostController): RouteDefinition {
		return {
			method: "GET",
			path: "/posts",
			handler: (req, res) => postController.list(req, res)
		};
	}
	@IntoSet @Provides static postControllerPostCreate(postController: PostController): RouteDefinition {
		return {
			method: "POST",
			path: "/posts",
			handler: (req, res) => postController.create(req, res)
		};
	}
	@IntoSet @Provides static userControllerGetById(userController: UserController): RouteDefinition {
		return {
			method: "GET",
			path: "/users/:id",
			handler: (req, res) => userController.byId(req, res)
		};
	}
	@IntoSet @Provides static userControllerPostCreate(userController: UserController): RouteDefinition {
		return {
			method: "POST",
			path: "/users",
			handler: (req, res) => userController.create(req, res)
		};
	}
	@IntoSet @Provides static userControllerDeleteRemove(userController: UserController): RouteDefinition {
		return {
			method: "DELETE",
			path: "/users/:id",
			handler: (req, res) => userController.remove(req, res)
		};
	}
}
