// This file is auto-generated by @hey-api/openapi-ts

import { type Options, todoControllerGetList, todoControllerPostCreate, todoControllerDeleteRemove, todoControllerGetById, todoControllerPutUpdate } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { TodoControllerGetListData, TodoControllerPostCreateData, TodoControllerPostCreateResponse, TodoControllerDeleteRemoveData, TodoControllerDeleteRemoveResponse, TodoControllerGetByIdData, TodoControllerPutUpdateData, TodoControllerPutUpdateResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const todoControllerGetListQueryKey = (options?: Options<TodoControllerGetListData>) => createQueryKey('todoControllerGetList', options);

export const todoControllerGetListOptions = (options?: Options<TodoControllerGetListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await todoControllerGetList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: todoControllerGetListQueryKey(options)
    });
};

export const todoControllerPostCreateQueryKey = (options: Options<TodoControllerPostCreateData>) => createQueryKey('todoControllerPostCreate', options);

export const todoControllerPostCreateOptions = (options: Options<TodoControllerPostCreateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await todoControllerPostCreate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: todoControllerPostCreateQueryKey(options)
    });
};

export const todoControllerPostCreateMutation = (options?: Partial<Options<TodoControllerPostCreateData>>) => {
    const mutationOptions: UseMutationOptions<TodoControllerPostCreateResponse, DefaultError, Options<TodoControllerPostCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await todoControllerPostCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const todoControllerDeleteRemoveMutation = (options?: Partial<Options<TodoControllerDeleteRemoveData>>) => {
    const mutationOptions: UseMutationOptions<TodoControllerDeleteRemoveResponse, DefaultError, Options<TodoControllerDeleteRemoveData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await todoControllerDeleteRemove({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const todoControllerGetByIdQueryKey = (options: Options<TodoControllerGetByIdData>) => createQueryKey('todoControllerGetById', options);

export const todoControllerGetByIdOptions = (options: Options<TodoControllerGetByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await todoControllerGetById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: todoControllerGetByIdQueryKey(options)
    });
};

export const todoControllerPutUpdateMutation = (options?: Partial<Options<TodoControllerPutUpdateData>>) => {
    const mutationOptions: UseMutationOptions<TodoControllerPutUpdateResponse, DefaultError, Options<TodoControllerPutUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await todoControllerPutUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};