// AUTO-GENERATED by anvil-bellows v0.0.3. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { AdminController } from "./admin-controller";
import type { RoleAuthz, SessionAuthn } from "./auth-services";
export @Module class RoutesModule {
	@IntoSet @Provides static adminControllerGetDashboard(adminController: AdminController, sessionAuthn: SessionAuthn): RouteDefinition {
		return {
			method: "GET",
			path: "/admin/dashboard",
			authn: [sessionAuthn],
			handler: (req, res) => adminController.dashboard(req, res)
		};
	}
	@IntoSet @Provides static adminControllerGetStats(adminController: AdminController, sessionAuthn: SessionAuthn, roleAuthz: RoleAuthz): RouteDefinition {
		return {
			method: "GET",
			path: "/admin/stats",
			authn: [sessionAuthn],
			authz: [roleAuthz],
			handler: (req, res) => adminController.stats(req, res)
		};
	}
}
