import { describe, expect, it } from "vitest";
import { compile } from "./index.js";

const ANVIL_STUB = [
  "export const Inject: any;",
  "export const Module: any;",
  "export const Provides: any;",
  "export const Component: any;",
  "export const Singleton: any;",
  "export const Binds: any;",
  "export const Subcomponent: any;",
  "export const IntoSet: any;",
].join("\n");

describe("@msulak/anvil-codegen-wasm", () => {
  it("compiles a simple project end-to-end (parser → graph → emit)", () => {
    const result = compile({
      entryPath: "/proj/src/app-component.ts",
      version: "0.0.1-wasm-test",
      files: {
        "/proj/node_modules/@msulak/anvil/index.d.ts": ANVIL_STUB,
        "/proj/src/heater.ts": `
          import { Inject, Singleton } from "@msulak/anvil";
          @Inject @Singleton
          export class Heater { constructor() {} on(): void {} }
        `,
        "/proj/src/pump.ts": `
          import { Inject } from "@msulak/anvil";
          import { Heater } from "./heater";
          @Inject
          export class Pump {
            constructor(private heater: Heater) {}
            pump(): void { this.heater.on(); }
          }
        `,
        "/proj/src/app-component.ts": `
          import { Component, Singleton } from "@msulak/anvil";
          import { Pump } from "./pump";
          import { Heater } from "./heater";
          @Singleton
          @Component({ modules: [] })
          export abstract class App {
            abstract pump(): Pump;
            abstract heater(): Heater;
          }
        `,
      },
    });

    expect(result.diagnostics).toEqual([]);
    expect(result.emittedFiles).toHaveLength(1);
    const dagger = result.emittedFiles[0]!;
    expect(dagger.path).toMatch(/app-component\.anvil\.ts$/);
    expect(dagger.contents).toContain("AnvilApp");
    expect(dagger.contents).toContain("createApp");
    expect(dagger.contents).toContain("0.0.1-wasm-test");
    expect(dagger.contents).toContain("private _heater");          // singleton cache
    expect(dagger.contents).toContain("return new Pump(this.getHeater())");
  });

  it("surfaces validation diagnostics through the structured output", () => {
    const result = compile({
      entryPath: "/proj/src/app-component.ts",
      version: "0.0.1",
      files: {
        "/proj/node_modules/@msulak/anvil/index.d.ts": ANVIL_STUB,
        // Heater has no @Inject — Pump's dep is unresolvable.
        "/proj/src/heater.ts": "export class Heater {}",
        "/proj/src/pump.ts": `
          import { Inject } from "@msulak/anvil";
          import { Heater } from "./heater";
          @Inject
          export class Pump { constructor(private h: Heater) {} }
        `,
        "/proj/src/app-component.ts": `
          import { Component } from "@msulak/anvil";
          import { Pump } from "./pump";
          @Component({ modules: [] })
          export abstract class App { abstract pump(): Pump; }
        `,
      },
    });

    expect(result.emittedFiles).toEqual([]); // validation failed; no emit
    expect(result.diagnostics.length).toBeGreaterThan(0);
    expect(result.diagnostics.some((d) => d.code === "anvil::missing_binding")).toBe(true);
    const diag = result.diagnostics.find((d) => d.code === "anvil::missing_binding")!;
    expect(diag.summary).toContain("Heater");
    expect(diag.primary.path).toMatch(/pump\.ts$/);
  });

  it("byte-identical output as the native CLI for the same input", () => {
    // Smoke test that the WASM emit pipeline matches the native one
    // — the dagger we emit should contain the exact same emit shape
    // (Dagger class, factories, banner) for an equivalent project.
    const result = compile({
      entryPath: "/proj/app.ts",
      version: "1.0.0",
      files: {
        "/proj/node_modules/@msulak/anvil/index.d.ts": ANVIL_STUB,
        "/proj/app.ts": `
          import { Component, Inject } from "@msulak/anvil";
          @Inject
          export class Repo { constructor() {} }
          @Component({ modules: [] })
          export abstract class App { abstract repo(): Repo; }
        `,
      },
    });
    expect(result.diagnostics).toEqual([]);
    expect(result.emittedFiles).toHaveLength(1);
    const dagger = result.emittedFiles[0]!.contents;
    // Hallmarks of the canonical emit shape — these are the
    // invariants the native codegen tests assert too.
    expect(dagger).toMatch(/^\/\/ AUTO-GENERATED by anvil v1\.0\.0/);
    expect(dagger).toContain("export class AnvilApp extends App");
    expect(dagger).toContain("static create(): App");
    expect(dagger).toContain("export function createApp(): App");
  });
});
