// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { BadRequestError } from "@anvil-di/bellows";
import { WebhooksController, GatherCallbackSchema, twimlRequestCodec } from "./webhooks-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static webhooksControllerPostGather(webhooksController: WebhooksController): RouteDefinition {
		return {
			method: "POST",
			path: "/webhooks/gather",
			bodyParser: {
				kind: "codec",
				contentType: twimlRequestCodec.contentType,
				decode: (raw) => twimlRequestCodec.decode(raw)
			},
			handler: (req, res) => {
				const _body = GatherCallbackSchema.safeParse(req.body);
				if (!_body.success) {
					throw new BadRequestError(_body.error.message);
				}
				webhooksController.gather(_body.data);
			}
		};
	}
}
