// AUTO-GENERATED by anvil v0.0.4. Do not edit.
// Source: ./coffee-component.ts
import { CoffeeShop } from "./coffee-component";
import { Heater } from "./heater";
import { Pump } from "./pump";
export class AnvilCoffeeShop extends CoffeeShop {
	private _heater: Heater | undefined;
	private getHeater(): Heater {
		return this._heater ??= new Heater();
	}
	private getPump(): Pump {
		return new Pump(this.getHeater());
	}
	pump(): Pump {
		return this.getPump();
	}
	heater(): Heater {
		return this.getHeater();
	}
	static create(): CoffeeShop {
		return new AnvilCoffeeShop();
	}
}
export function createCoffeeShop(): CoffeeShop {
	return AnvilCoffeeShop.create();
}
