// AUTO-GENERATED by anvil v0.0.1. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import type { Plugin } from "./plugin";
import { PluginsModule } from "./plugins-module";
export class DaggerAppComponent extends AppComponent {
	private getSetOfPlugin(): Set<Plugin> {
		return new Set([PluginsModule.auth(), PluginsModule.logging()]);
	}
	plugins(): Set<Plugin> {
		return this.getSetOfPlugin();
	}
	static create(): AppComponent {
		return new DaggerAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return DaggerAppComponent.create();
}
