// AUTO-GENERATED by anvil-bellows v0.0.1. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/anvil-bellows";
import { OrderController, CreateOrderBody, OrderSchema, OrderFilterQuery, OrderParams } from "./order-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static orderControllerPostCreate(orderController: OrderController): RouteDefinition {
		return {
			method: "POST",
			path: "/orders",
			handler: (req, res) => {
				const _body = CreateOrderBody.safeParse(req.body);
				if (!_body.success) {
					res.status(400).json(_body.error);
					return;
				}
				const _result = orderController.create(_body.data);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerGetList(orderController: OrderController): RouteDefinition {
		return {
			method: "GET",
			path: "/orders",
			handler: (req, res) => {
				const _query = OrderFilterQuery.safeParse(req.query);
				if (!_query.success) {
					res.status(400).json(_query.error);
					return;
				}
				const _result = orderController.list(_query.data);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerGetById(orderController: OrderController): RouteDefinition {
		return {
			method: "GET",
			path: "/orders/:id",
			handler: (req, res) => {
				const _params = OrderParams.safeParse(req.params);
				if (!_params.success) {
					res.status(400).json(_params.error);
					return;
				}
				const _result = orderController.byId(_params.data, req);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerDeleteRemove(orderController: OrderController): RouteDefinition {
		return {
			method: "DELETE",
			path: "/orders/:id",
			handler: (req, res) => {
				const _params = OrderParams.safeParse(req.params);
				if (!_params.success) {
					res.status(400).json(_params.error);
					return;
				}
				orderController.remove(_params.data, res);
			}
		};
	}
}
