// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { BadRequestError, InternalServerError } from "@anvil-di/bellows";
import { OrderController, CreateOrderBody, OrderSchema, OrderFilterQuery, OrderParams } from "./order-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static orderControllerPostCreate(orderController: OrderController): RouteDefinition {
		return {
			method: "POST",
			path: "/orders",
			bodyParser: "json",
			handler: (req, res) => {
				const _body = CreateOrderBody.safeParse(req.body);
				if (!_body.success) {
					throw new BadRequestError(_body.error.message);
				}
				const _result = orderController.create(_body.data);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					throw new InternalServerError(_validated.error.message);
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerGetList(orderController: OrderController): RouteDefinition {
		return {
			method: "GET",
			path: "/orders",
			handler: (req, res) => {
				const _query = OrderFilterQuery.safeParse(req.query);
				if (!_query.success) {
					throw new BadRequestError(_query.error.message);
				}
				const _result = orderController.list(_query.data);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					throw new InternalServerError(_validated.error.message);
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerGetById(orderController: OrderController): RouteDefinition {
		return {
			method: "GET",
			path: "/orders/:id",
			handler: (req, res) => {
				const _params = OrderParams.safeParse(req.params);
				if (!_params.success) {
					throw new BadRequestError(_params.error.message);
				}
				const _result = orderController.byId(_params.data, req);
				const _validated = OrderSchema.safeParse(_result);
				if (!_validated.success) {
					throw new InternalServerError(_validated.error.message);
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static orderControllerDeleteRemove(orderController: OrderController): RouteDefinition {
		return {
			method: "DELETE",
			path: "/orders/:id",
			handler: (req, res) => {
				const _params = OrderParams.safeParse(req.params);
				if (!_params.success) {
					throw new BadRequestError(_params.error.message);
				}
				orderController.remove(_params.data, res);
			}
		};
	}
}
