// AUTO-GENERATED by anvil v0.0.4. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import type { Config } from "./config";
import { ConfigModule } from "./config-module";
import type { Database } from "./database";
import { DatabaseModule } from "./database-module";
import { UserService } from "./user-service";
export class AnvilAppComponent extends AppComponent {
	private _config: Config | undefined;
	private _database: Database | undefined;
	private getConfig(): Config {
		return this._config!;
	}
	private getDatabase(): Database {
		return this._database!;
	}
	private getUserService(): UserService {
		return new UserService(this.getDatabase());
	}
	static async _resolve(d: AnvilAppComponent): Promise<void> {
		d._config = await ConfigModule.loadConfig();
		d._database = await DatabaseModule.openDatabase(d.getConfig());
	}
	config(): Config {
		return this.getConfig();
	}
	database(): Database {
		return this.getDatabase();
	}
	userService(): UserService {
		return this.getUserService();
	}
	static async create(): Promise<AppComponent> {
		const d = new AnvilAppComponent();
		await AnvilAppComponent._resolve(d);
		return d;
	}
}
export async function createAppComponent(): Promise<AppComponent> {
	return AnvilAppComponent.create();
}
