// AUTO-GENERATED by anvil-bellows v0.0.3. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { BadRequestError, InternalServerError } from "@anvil-di/bellows";
import { WebhooksController, GatherWebhookBody, TwimlResponseSchema, twimlCodec } from "./webhooks-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static webhooksControllerPostGather(webhooksController: WebhooksController): RouteDefinition {
		return {
			method: "POST",
			path: "/webhooks/gather",
			handler: async (req, res) => {
				const _body = GatherWebhookBody.safeParse(req.body);
				if (!_body.success) {
					throw new BadRequestError(_body.error.message);
				}
				const _result = await webhooksController.gather(_body.data);
				const _validated = TwimlResponseSchema.safeParse(_result);
				if (!_validated.success) {
					throw new InternalServerError(_validated.error.message);
				}
				res.type(twimlCodec.contentType).send(twimlCodec.encode(_validated.data));
			}
		};
	}
}
