// AUTO-GENERATED by tsdi v0.0.1. Do not edit.
// Source: ./coffee-component.ts
import { CoffeeShop } from "./coffee-component";
import { ElectricHeater } from "./electric-heater";
import { Heater } from "./heater";
export class DaggerCoffeeShop extends CoffeeShop {
	private getElectricHeater(): ElectricHeater {
		return new ElectricHeater();
	}
	private getHeater(): Heater {
		return this.getElectricHeater();
	}
	heater(): Heater {
		return this.getHeater();
	}
	static create(): CoffeeShop {
		return new DaggerCoffeeShop();
	}
}
export function createCoffeeShop(): CoffeeShop {
	return DaggerCoffeeShop.create();
}
