// AUTO-GENERATED by anvil v0.0.3. Do not edit.
// Source: ./coffee-component.ts
import { CoffeeShop } from "./coffee-component";
import { ElectricHeater } from "./electric-heater";
import type { Heater } from "./heater";
export class AnvilCoffeeShop extends CoffeeShop {
	private getElectricHeater(): ElectricHeater {
		return new ElectricHeater();
	}
	private getHeater(): Heater {
		return this.getElectricHeater();
	}
	heater(): Heater {
		return this.getHeater();
	}
	static create(): CoffeeShop {
		return new AnvilCoffeeShop();
	}
}
export function createCoffeeShop(): CoffeeShop {
	return AnvilCoffeeShop.create();
}
