//! Integration tests for `anvil build` (M4).
//!
//! Materializes a small TypeScript project into a tempdir, runs the CLI,
//! and asserts that:
//! - the expected `<component>.anvil.ts` file appears next to the source,
//! - it carries the banner and source comment,
//! - it imports the expected types and exports `Dagger<X>` + `create<X>`.

use std::path::{Path, PathBuf};

use assert_cmd::Command;
use predicates::prelude::PredicateBooleanExt;
use predicates::str::contains;
use tempfile::TempDir;

fn write_project(tmp: &TempDir, files: &[(&str, &str)]) -> PathBuf {
    let root = tmp.path().to_path_buf();
    for (rel, contents) in files {
        let dst = root.join(rel);
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(&dst, contents).unwrap();
    }
    root
}

fn write_anvil_stub(root: &Path) {
    let pkg = root.join("node_modules/@anvil-di/anvil");
    std::fs::create_dir_all(&pkg).unwrap();
    std::fs::write(
        pkg.join("package.json"),
        r#"{ "name": "@anvil-di/anvil", "main": "index.ts" }"#,
    )
    .unwrap();
    std::fs::write(
        pkg.join("index.ts"),
        "export const Inject = (..._: any[]) => {};\n\
         export const Module = (..._: any[]) => {};\n\
         export const Provides = (..._: any[]) => {};\n\
         export const Component = (..._: any[]) => {};\n\
         export const Singleton = (..._: any[]) => {};\n\
         export const Binds = (..._: any[]) => {};\n",
    )
    .unwrap();
}

#[test]
fn build_emits_anvil_file_next_to_component() {
    let tmp = TempDir::new().unwrap();
    let root = write_project(
        &tmp,
        &[
            (
                "src/heater.ts",
                r#"
                    import { Inject } from "@anvil-di/anvil";
                    @Inject
                    export class Heater { constructor() {} }
                "#,
            ),
            (
                "src/pump.ts",
                r#"
                    import { Inject } from "@anvil-di/anvil";
                    import { Heater } from "./heater";
                    @Inject
                    export class Pump { constructor(private h: Heater) {} }
                "#,
            ),
            (
                "src/coffee-component.ts",
                r#"
                    import { Component } from "@anvil-di/anvil";
                    import { Pump } from "./pump";
                    import { Heater } from "./heater";
                    @Component({ modules: [] })
                    export abstract class CoffeeShop {
                        abstract pump(): Pump;
                        abstract heater(): Heater;
                    }
                "#,
            ),
        ],
    );
    write_anvil_stub(&root);

    let entry = root.join("src/coffee-component.ts");
    Command::cargo_bin("anvil")
        .unwrap()
        .arg("build")
        .arg("--entry")
        .arg(&entry)
        .assert()
        .success()
        .stdout(contains("emitted").and(contains("coffee-component.anvil.ts")));

    let out = root.join("src/coffee-component.anvil.ts");
    assert!(out.exists(), "expected {} to exist", out.display());
    let body = std::fs::read_to_string(&out).unwrap();

    // Banner + source comment.
    assert!(body.contains("AUTO-GENERATED by anvil"), "body: {body}");
    assert!(body.contains("Source:"), "body: {body}");
    // Class/factory shape.
    assert!(body.contains("AnvilCoffeeShop"), "body: {body}");
    assert!(body.contains("extends CoffeeShop"), "body: {body}");
    assert!(body.contains("createCoffeeShop"), "body: {body}");
    // Imports use stripped specifiers.
    assert!(body.contains("from \"./heater\""), "body: {body}");
    assert!(body.contains("from \"./pump\""), "body: {body}");
    assert!(body.contains("from \"./coffee-component\""), "body: {body}");
}

#[test]
fn build_refuses_to_emit_on_validation_failure() {
    let tmp = TempDir::new().unwrap();
    let root = write_project(
        &tmp,
        &[
            // Heater without @Inject ctor → MissingBinding when Pump asks for it.
            ("src/heater.ts", "export class Heater {}\n"),
            (
                "src/pump.ts",
                r#"
                    import { Inject } from "@anvil-di/anvil";
                    import { Heater } from "./heater";
                    @Inject
                    export class Pump { constructor(private h: Heater) {} }
                "#,
            ),
            (
                "src/coffee-component.ts",
                r#"
                    import { Component } from "@anvil-di/anvil";
                    import { Pump } from "./pump";
                    @Component({ modules: [] })
                    export abstract class CoffeeShop { abstract pump(): Pump; }
                "#,
            ),
        ],
    );
    write_anvil_stub(&root);

    let entry = root.join("src/coffee-component.ts");
    Command::cargo_bin("anvil")
        .unwrap()
        .arg("build")
        .arg("--entry")
        .arg(&entry)
        .assert()
        .failure()
        .stderr(contains("missing binding"));

    // No file should have been written.
    assert!(!root.join("src/coffee-component.anvil.ts").exists());
}
