// AUTO-GENERATED by anvil-bellows v0.0.1. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/anvil-bellows";
import { HealthController } from "./good-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static healthControllerGetPing(healthController: HealthController): RouteDefinition {
		return {
			method: "GET",
			path: "/health",
			handler: (req, res) => healthController.ping(req, res)
		};
	}
}
