// AUTO-GENERATED by anvil v0.0.4. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import { AppModule } from "./app-module";
import { ConsoleLogger } from "./console-logger";
import { HealthController } from "./health-controller";
import type { Logger } from "./logger";
import type { RouteRegistrar } from "./route-registrar";
import { UserController } from "./user-controller";
import { UserRepository } from "./user-repository";
import { UserService } from "./user-service";
export class AnvilAppComponent extends AppComponent {
	private _consoleLogger: ConsoleLogger | undefined;
	private _healthController: HealthController | undefined;
	private _userRepository: UserRepository | undefined;
	private _userController: UserController | undefined;
	private getConsoleLogger(): ConsoleLogger {
		return this._consoleLogger ??= new ConsoleLogger();
	}
	private getHealthController(): HealthController {
		return this._healthController ??= new HealthController();
	}
	private getLogger(): Logger {
		return this.getConsoleLogger();
	}
	private getUserRepository(): UserRepository {
		return this._userRepository ??= new UserRepository();
	}
	private getUserService(): UserService {
		return new UserService(this.getUserRepository(), this.getLogger());
	}
	private getUserController(): UserController {
		return this._userController ??= new UserController(this.getUserService(), this.getLogger());
	}
	private getSetOfRouteRegistrar(): Set<RouteRegistrar> {
		return new Set([AppModule.provideUserRoutes(this.getUserController()), AppModule.provideHealthRoutes(this.getHealthController())]);
	}
	logger(): Logger {
		return this.getLogger();
	}
	routes(): Set<RouteRegistrar> {
		return this.getSetOfRouteRegistrar();
	}
	static create(): AppComponent {
		return new AnvilAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return AnvilAppComponent.create();
}
