// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { AdminController, auditLog } from "./admin-controller";
import { requireAdmin, requireAuth } from "./auth-middleware";
export @Module class RoutesModule {
	@IntoSet @Provides static adminControllerGetDashboard(adminController: AdminController): RouteDefinition {
		return {
			method: "GET",
			path: "/admin/dashboard",
			middleware: [requireAuth],
			handler: (req, res) => adminController.dashboard(req, res)
		};
	}
	@IntoSet @Provides static adminControllerGetStats(adminController: AdminController): RouteDefinition {
		return {
			method: "GET",
			path: "/admin/stats",
			middleware: [
				requireAuth,
				requireAdmin,
				auditLog
			],
			handler: (req, res) => adminController.stats(req, res)
		};
	}
}
