// AUTO-GENERATED by anvil v0.0.1. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import { ConsoleLogger } from "./console-logger";
import type { Logger } from "./logger";
import { RequestComponent } from "./request-component";
import type { RequestContext } from "./request-context";
import { RequestModule } from "./request-module";
import { UserController } from "./user-controller";
import { UserRepository } from "./user-repository";
import type { Request, Response } from "express";
export class AnvilAppComponent extends AppComponent {
	private _consoleLogger: ConsoleLogger | undefined;
	private _userRepository: UserRepository | undefined;
	private getConsoleLogger(): ConsoleLogger {
		return this._consoleLogger ??= new ConsoleLogger();
	}
	getLogger(): Logger {
		return this.getConsoleLogger();
	}
	getUserRepository(): UserRepository {
		return this._userRepository ??= new UserRepository();
	}
	logger(): Logger {
		return this.getLogger();
	}
	requestComponent(req: Request, res: Response): RequestComponent {
		return new AnvilRequestComponent(this, req, res);
	}
	static create(): AppComponent {
		return new AnvilAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return AnvilAppComponent.create();
}
export class AnvilRequestComponent extends RequestComponent {
	constructor(private parent: AnvilAppComponent, private req: Request, private res: Response) {
		super();
	}
	private getRequest(): Request {
		return this.req;
	}
	private getRequestContext(): RequestContext {
		return RequestModule.context(this.getRequest());
	}
	private getResponse(): Response {
		return this.res;
	}
	private getUserController(): UserController {
		return new UserController(this.getRequestContext(), this.getResponse(), this.parent.getLogger(), this.parent.getUserRepository());
	}
	userController(): UserController {
		return this.getUserController();
	}
	context(): RequestContext {
		return this.getRequestContext();
	}
}
