// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { Module, Provides, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { BadRequestError } from "@anvil-di/bellows";
import { WebhooksController, GatherBody, SignatureHeaders } from "./webhooks-controller";
export @Module class RoutesModule {
	@IntoSet @Provides static webhooksControllerPostGather(webhooksController: WebhooksController): RouteDefinition {
		return {
			method: "POST",
			path: "/webhooks/gather",
			bodyParser: "urlencoded",
			handler: (req, res) => {
				const _body = GatherBody.safeParse(req.body);
				if (!_body.success) {
					throw new BadRequestError(_body.error.message);
				}
				const _headers = SignatureHeaders.safeParse(req.headers);
				if (!_headers.success) {
					throw new BadRequestError(_headers.error.message);
				}
				webhooksController.gather(_body.data, _headers.data, req.rawBody);
			}
		};
	}
}
