//! Emit `routes.module.ts` from parsed controller metadata.
//!
//! Follows the same strategy as `anvil-codegen`: build the TypeScript source as
//! a [`String`], validate it by parsing with Oxc, then re-emit with
//! `oxc_codegen::Codegen` for canonical formatting. The banner is prepended as
//! raw text (Codegen strips comments).

use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use oxc_allocator::Allocator;
use oxc_codegen::Codegen;
use oxc_parser::Parser;
use oxc_span::SourceType;
use thiserror::Error;

use crate::parser::ControllerFile;

/// Banner prepended to every generated file.
pub const BANNER: &str = "// AUTO-GENERATED by anvil-bellows. Do not edit.\n";

/// All ways code emission can fail.
#[derive(Debug, Error)]
pub enum EmitError {
    /// The string-built TS failed to parse — this is a codegen bug.
    #[error("emitter produced unparseable TypeScript: {errors:?}")]
    EmittedSyntaxError {
        /// Oxc parser error messages.
        errors: Vec<String>,
    },
}

/// Emit a `routes.module.ts` file.
///
/// `output_path` is where the file will be written; it is used to compute
/// relative import specifiers. `controller_files` is the parsed metadata from
/// [`crate::parser::parse_entry`].
///
/// # Errors
///
/// Returns [`EmitError`] if the generated TypeScript fails Oxc's parser (a
/// codegen invariant — should never happen with valid input).
pub fn emit_routes_module(
    controller_files: &[ControllerFile],
    output_path: &Path,
    version: &str,
) -> Result<String, EmitError> {
    let out_dir = output_path
        .parent()
        .unwrap_or_else(|| Path::new("."));

    let body = build_ts(controller_files, out_dir);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, &body, SourceType::ts()).parse();
    if !ret.errors.is_empty() {
        return Err(EmitError::EmittedSyntaxError {
            errors: ret.errors.iter().map(|e| format!("{e:?}")).collect(),
        });
    }
    let canonical = Codegen::new().build(&ret.program).code;

    let mut output = String::new();
    writeln!(output, "// AUTO-GENERATED by anvil-bellows v{version}. Do not edit.")
        .expect("write to String");
    output.push_str(&canonical);
    Ok(output)
}

/// Build the raw TypeScript source string (before oxc canonicalization).
fn build_ts(files: &[ControllerFile], out_dir: &Path) -> String {
    let mut s = String::new();

    // Imports from @msulak/anvil and @msulak/anvil-bellows.
    s.push_str("import { Module, Provides, IntoSet } from \"@msulak/anvil\";\n");
    s.push_str("import type { RouteDefinition } from \"@msulak/anvil-bellows\";\n");

    // One import per controller file.
    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            writeln!(
                s,
                "import {{ {} }} from \"{specifier}\";",
                ctrl.class_name
            )
            .unwrap();
        }
    }

    s.push('\n');
    s.push_str("@Module\n");
    s.push_str("export class RoutesModule {\n");

    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        let _ = specifier; // used above; here we emit methods
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                let method_name = provider_method_name(&ctrl.class_name, route.method.decorator_name(), &route.handler_name);
                let param_name = lower_first(&ctrl.class_name);
                let class_name = &ctrl.class_name;
                let http_verb = route.method.http_verb();
                let path = &route.path;
                let handler = &route.handler_name;

                writeln!(
                    s,
                    "  @IntoSet @Provides\n  static {method_name}({param_name}: {class_name}): RouteDefinition {{\n    return {{\n      method: \"{http_verb}\",\n      path: \"{path}\",\n      handler: (req, res) => {param_name}.{handler}(req, res),\n    }};\n  }}"
                )
                .unwrap();
            }
        }
    }

    s.push_str("}\n");
    s
}

/// Generate the provider static method name from controller class, decorator, and handler.
///
/// `UserController` + `Get` + `byId` → `userControllerGetById`
fn provider_method_name(class_name: &str, decorator: &str, handler: &str) -> String {
    format!(
        "{}{}{}",
        lower_first(class_name),
        decorator,
        upper_first(handler)
    )
}

/// Lower-case the first character of a string.
fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().to_string() + chars.as_str(),
    }
}

/// Upper-case the first character of a string.
fn upper_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

/// Compute a `./`-prefixed relative import specifier from `out_dir` to `source_path`,
/// stripping the `.ts` extension.
fn import_specifier(out_dir: &Path, source_path: &Path) -> String {
    let without_ext = strip_ts_extension(source_path);
    let rel = relative_path(out_dir, &without_ext)
        .unwrap_or_else(|| without_ext.clone());
    let raw = rel.to_string_lossy().replace('\\', "/");
    if raw.starts_with("./") || raw.starts_with("../") {
        raw
    } else {
        format!("./{raw}")
    }
}

/// Strip `.ts`, `.tsx`, or `.d.ts` from a path.
fn strip_ts_extension(path: &Path) -> PathBuf {
    let s = path.to_string_lossy();
    for suffix in [".d.ts", ".tsx", ".ts"] {
        if let Some(stripped) = s.strip_suffix(suffix) {
            return PathBuf::from(stripped);
        }
    }
    path.to_path_buf()
}

/// Compute a relative path from `from` (a directory) to `to` (a file path),
/// both expected to be absolute or consistently relative.
fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from_comps: Vec<Component<'_>> = from.components().collect();
    let to_comps: Vec<Component<'_>> = to.components().collect();
    let mut i = 0;
    while i < from_comps.len() && i < to_comps.len() && from_comps[i] == to_comps[i] {
        i += 1;
    }
    let mut rel = PathBuf::new();
    for _ in &from_comps[i..] {
        rel.push("..");
    }
    for comp in &to_comps[i..] {
        rel.push(comp);
    }
    if rel.as_os_str().is_empty() {
        None
    } else {
        Some(rel)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{Controller, HttpMethod, Route};

    fn make_file(path: &str, class: &str, routes: Vec<(&str, HttpMethod, &str)>) -> ControllerFile {
        ControllerFile {
            source_path: PathBuf::from(path),
            controllers: vec![Controller {
                class_name: class.to_owned(),
                routes: routes
                    .into_iter()
                    .map(|(p, m, h)| Route {
                        method: m,
                        path: p.to_owned(),
                        handler_name: h.to_owned(),
                    })
                    .collect(),
            }],
        }
    }

    #[test]
    fn provider_method_name_cases() {
        assert_eq!(
            provider_method_name("UserController", "Get", "byId"),
            "userControllerGetById"
        );
        assert_eq!(
            provider_method_name("PostController", "Post", "create"),
            "postControllerPostCreate"
        );
        assert_eq!(
            provider_method_name("HealthController", "Get", "ping"),
            "healthControllerGetPing"
        );
    }

    #[test]
    fn emit_single_controller() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![
                ("/users/:id", HttpMethod::Get, "byId"),
                ("/users", HttpMethod::Post, "create"),
            ],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("@Module"));
        assert!(result.contains("RoutesModule"));
        assert!(result.contains("userControllerGetById"));
        assert!(result.contains("userControllerPostCreate"));
        assert!(result.contains("\"GET\""));
        assert!(result.contains("\"/users/:id\""));
        assert!(result.contains("import { UserController }"));
        assert!(result.contains("\"./user-controller\""));
    }

    #[test]
    fn emit_multiple_controllers() {
        let files = vec![
            make_file(
                "/project/src/post-controller.ts",
                "PostController",
                vec![("/posts", HttpMethod::Get, "list")],
            ),
            make_file(
                "/project/src/user-controller.ts",
                "UserController",
                vec![("/users", HttpMethod::Get, "list")],
            ),
        ];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("PostController"));
        assert!(result.contains("UserController"));
        assert!(result.contains("postControllerGetList"));
        assert!(result.contains("userControllerGetList"));
    }
}
