//! Emit `routes.module.anvil.ts` and `schema-route.module.anvil.ts` from parsed
//! controller metadata.
//!
//! Follows the same strategy as `anvil-codegen`: build the TypeScript source as
//! a [`String`], validate it by parsing with Oxc, then re-emit with
//! `oxc_codegen::Codegen` for canonical formatting. The banner is prepended as
//! raw text (Codegen strips comments).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use oxc_allocator::Allocator;
use oxc_codegen::Codegen;
use oxc_parser::Parser;
use oxc_span::SourceType;
use thiserror::Error;

use crate::parser::{
    AuthRef, Controller, ControllerFile, CtorParam, HttpMethod, ImportOrigin, ParamKind,
    ReturnKind, Route,
};

/// Banner prepended to every generated file.
pub const BANNER: &str = "// AUTO-GENERATED by anvil-bellows. Do not edit.\n";

/// All ways code emission can fail.
#[derive(Debug, Error)]
pub enum EmitError {
    /// The string-built TS failed to parse — this is a codegen bug.
    #[error("emitter produced unparseable TypeScript: {errors:?}")]
    EmittedSyntaxError {
        /// Oxc parser error messages.
        errors: Vec<String>,
    },
}

/// Emit a `routes.module.ts` file.
///
/// `output_path` is where the file will be written; it is used to compute
/// relative import specifiers. `controller_files` is the parsed metadata from
/// [`crate::parser::parse_entry`].
///
/// # Errors
///
/// Returns [`EmitError`] if the generated TypeScript fails Oxc's parser (a
/// codegen invariant — should never happen with valid input).
pub fn emit_routes_module(
    controller_files: &[ControllerFile],
    output_path: &Path,
    version: &str,
) -> Result<String, EmitError> {
    let out_dir = output_path.parent().unwrap_or_else(|| Path::new("."));

    let body = build_ts(controller_files, out_dir);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, &body, SourceType::ts()).parse();
    if !ret.errors.is_empty() {
        return Err(EmitError::EmittedSyntaxError {
            errors: ret.errors.iter().map(|e| format!("{e:?}")).collect(),
        });
    }
    let canonical = Codegen::new().build(&ret.program).code;

    let mut output = String::new();
    writeln!(
        output,
        "// AUTO-GENERATED by anvil-bellows v{version}. Do not edit."
    )
    .expect("write to String");
    output.push_str(&canonical);
    Ok(output)
}

/// Build the raw TypeScript source string (before oxc canonicalization).
#[allow(clippy::too_many_lines, clippy::similar_names)]
fn build_ts(files: &[ControllerFile], out_dir: &Path) -> String {
    let mut s = String::new();

    let any_ctor_params = files
        .iter()
        .flat_map(|f| &f.controllers)
        .any(|c| !c.ctor_params.is_empty());
    let anvil_imports = if any_ctor_params {
        "Module, Provides, Singleton, IntoSet"
    } else {
        "Module, Provides, IntoSet"
    };
    writeln!(s, "import {{ {anvil_imports} }} from \"@anvil-di/anvil\";").unwrap();
    s.push_str("import type { RouteDefinition } from \"@anvil-di/bellows\";\n");

    // Value imports for the error classes thrown by generated validation
    // prologues/epilogues — only emitted when a route actually needs them.
    let routes_with_validation = files
        .iter()
        .flat_map(|f| &f.controllers)
        .flat_map(|c| &c.routes)
        .filter(|r| !r.params.is_empty() && all_params_recognized(r));
    let mut needs_bad_request_error = false;
    let mut needs_internal_server_error = false;
    for route in routes_with_validation {
        needs_bad_request_error |= route.params.iter().any(|p| {
            matches!(
                p.kind,
                ParamKind::Body(_)
                    | ParamKind::Query(_)
                    | ParamKind::Params(_)
                    | ParamKind::FormBody(_)
                    | ParamKind::Headers(_)
                    | ParamKind::Consumes { .. }
            )
        });
        needs_internal_server_error |= matches!(route.return_kind, ReturnKind::Responds { .. });
    }
    // SseStream/disconnectSignal are only referenced from the typed-adapter
    // path, same gating as the error classes above.
    let sse_params = files
        .iter()
        .flat_map(|f| &f.controllers)
        .flat_map(|c| &c.routes)
        .filter(|r| !r.params.is_empty() && all_params_recognized(r))
        .flat_map(|r| &r.params);
    let mut needs_sse_stream = false;
    let mut needs_disconnect_signal = false;
    for param in sse_params {
        needs_sse_stream |= matches!(param.kind, ParamKind::Sse);
        needs_disconnect_signal |= matches!(param.kind, ParamKind::Sse | ParamKind::Signal);
    }
    let mut bellows_value_imports: Vec<&str> = Vec::new();
    if needs_bad_request_error {
        bellows_value_imports.push("BadRequestError");
    }
    if needs_internal_server_error {
        bellows_value_imports.push("InternalServerError");
    }
    if needs_sse_stream {
        bellows_value_imports.push("SseStream");
    }
    if needs_disconnect_signal {
        bellows_value_imports.push("disconnectSignal");
    }
    if !bellows_value_imports.is_empty() {
        writeln!(
            s,
            "import {{ {} }} from \"@anvil-di/bellows\";",
            bellows_value_imports.join(", ")
        )
        .unwrap();
    }

    // One import per controller file — includes controller class + any schema refs.
    // Also collect dep types that need separate imports.
    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        // Collect all identifiers to import from this file.
        let mut imports: Vec<String> = Vec::new();
        for ctrl in &file.controllers {
            imports.push(ctrl.class_name.clone());
            for route in &ctrl.routes {
                collect_schema_refs(route, &mut imports);
                for mw in &route.middleware {
                    if mw.origin.is_none() && !imports.contains(&mw.name) {
                        imports.push(mw.name.clone());
                    }
                }
                for a in route.authn.iter().chain(&route.authz) {
                    if a.origin.is_none() && !imports.contains(&a.name) {
                        imports.push(a.name.clone());
                    }
                }
            }
        }
        imports.dedup();
        writeln!(
            s,
            "import {{ {} }} from \"{specifier}\";",
            imports.join(", ")
        )
        .unwrap();
    }

    // Emit imports for controller dep types that come from other files —
    // either a relative source file or a bare/scoped package specifier (same
    // two origins `@Middleware`/`@Authn`/`@Authz` refs resolve below). Group
    // by resolved specifier so we emit one import per source.
    let mut dep_imports: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for cp in &ctrl.ctor_params {
                let spec = match &cp.origin {
                    Some(ImportOrigin::Relative(abs)) => import_specifier(out_dir, abs),
                    Some(ImportOrigin::Package(pkg)) => pkg.clone(),
                    None => continue,
                };
                // Skip if the dep type is already imported from the controller file.
                if spec == ctrl_spec {
                    continue;
                }
                dep_imports
                    .entry(spec)
                    .or_default()
                    .push(cp.type_name.clone());
            }
        }
    }
    for (spec, mut names) in dep_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import type {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    // Emit imports for middleware functions that aren't declared in the
    // controller's own file — grouped by resolved specifier (relative file or
    // bare package), one import per specifier.
    let mut middleware_imports: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                for mw in &route.middleware {
                    let spec = match &mw.origin {
                        Some(ImportOrigin::Relative(abs)) => import_specifier(out_dir, abs),
                        Some(ImportOrigin::Package(pkg)) => pkg.clone(),
                        None => continue, // declared in the controller file — handled above
                    };
                    if spec == ctrl_spec {
                        continue;
                    }
                    middleware_imports
                        .entry(spec)
                        .or_default()
                        .push(mw.name.clone());
                }
            }
        }
    }
    for (spec, mut names) in middleware_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    // Emit type-only imports for @Authn/@Authz service classes that aren't
    // declared in the controller's own file — these are only ever used in a
    // type-annotation position on the generated provider method, never
    // called as a value, so `import type` is always correct here (unlike
    // middleware, which is imported as a value).
    let mut auth_imports: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                for a in route.authn.iter().chain(&route.authz) {
                    let spec = match &a.origin {
                        Some(ImportOrigin::Relative(abs)) => import_specifier(out_dir, abs),
                        Some(ImportOrigin::Package(pkg)) => pkg.clone(),
                        None => continue, // declared in the controller file — handled above
                    };
                    if spec == ctrl_spec {
                        continue;
                    }
                    auth_imports.entry(spec).or_default().push(a.name.clone());
                }
            }
        }
    }
    for (spec, mut names) in auth_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import type {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    s.push('\n');
    s.push_str("@Module\n");
    s.push_str("export class RoutesModule {\n");

    for file in files {
        for ctrl in &file.controllers {
            // Emit a @Singleton @Provides binding for the controller itself,
            // taking its constructor deps as DI parameters.
            if !ctrl.ctor_params.is_empty() {
                emit_controller_provider(&mut s, ctrl.class_name.as_str(), &ctrl.ctor_params);
            }

            for route in &ctrl.routes {
                let method_name = provider_method_name(
                    &ctrl.class_name,
                    route.method.decorator_name(),
                    &route.handler_name,
                );
                let param_name = lower_first(&ctrl.class_name);
                let class_name = &ctrl.class_name;
                let http_verb = route.method.http_verb();
                let path = &route.path;

                let handler_body = emit_handler(&param_name, &route.handler_name, route);
                let middleware_field = if route.middleware.is_empty() {
                    String::new()
                } else {
                    let names: Vec<&str> =
                        route.middleware.iter().map(|m| m.name.as_str()).collect();
                    format!("\n      middleware: [{}],", names.join(", "))
                };
                let authn_field = auth_field("authn", &route.authn);
                let authz_field = auth_field("authz", &route.authz);
                let extra_params_sig = extra_auth_params_sig(route);
                let body_parser_field = match route_body_parser(route) {
                    Some(BodyParserKind::Named(kind)) => format!("\n      bodyParser: \"{kind}\","),
                    Some(BodyParserKind::Codec(codec_ident)) => format!(
                        "\n      bodyParser: {{ kind: \"codec\", contentType: {codec_ident}.contentType, decode: (raw) => {codec_ident}.decode(raw) }},"
                    ),
                    None => String::new(),
                };

                writeln!(
                    s,
                    "  @IntoSet @Provides\n  static {method_name}({param_name}: {class_name}{extra_params_sig}): RouteDefinition {{\n    return {{\n      method: \"{http_verb}\",\n      path: \"{path}\",{middleware_field}{authn_field}{authz_field}{body_parser_field}\n      handler: {handler_body},\n    }};\n  }}"
                )
                .unwrap();
            }
        }
    }

    s.push_str("}\n");
    s
}

/// Render the `authn: [...]`/`authz: [...]` `RouteDefinition` field, or an
/// empty string when `refs` is empty (field omitted entirely).
fn auth_field(field_name: &str, refs: &[AuthRef]) -> String {
    if refs.is_empty() {
        return String::new();
    }
    let names: Vec<String> = refs.iter().map(|a| lower_first(&a.name)).collect();
    format!("\n      {field_name}: [{}],", names.join(", "))
}

/// Build the extra `, local: ClassName` DI parameters a route's provider
/// method needs for its `@Authn`/`@Authz` service classes, deduped by class
/// name (a class referenced by both decorators gets one shared parameter).
fn extra_auth_params_sig(route: &Route) -> String {
    let mut seen: Vec<&str> = Vec::new();
    let mut sig = String::new();
    for a in route.authn.iter().chain(&route.authz) {
        if seen.contains(&a.name.as_str()) {
            continue;
        }
        seen.push(&a.name);
        write!(sig, ", {}: {}", lower_first(&a.name), a.name).unwrap();
    }
    sig
}

/// Emit a `@Singleton @Provides` method that constructs a controller from its deps.
fn emit_controller_provider(s: &mut String, class_name: &str, ctor_params: &[CtorParam]) {
    let method_name = lower_first(class_name);
    let params_sig = ctor_params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.type_name))
        .collect::<Vec<_>>()
        .join(", ");
    let ctor_args = ctor_params
        .iter()
        .map(|p| p.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        s,
        "  @Singleton @Provides\n  static {method_name}({params_sig}): {class_name} {{\n    return new {class_name}({ctor_args});\n  }}"
    )
    .unwrap();
}

/// Emit a `schema-route.module.anvil.ts` alongside `routes.module.anvil.ts`.
///
/// The generated module exports `OpenApiModule` — an `@Module` class with a single
/// `@IntoSet @Provides` method that provides a `GET /openapi.json` route whose
/// handler calls `buildSpec()`. `buildSpec()` constructs the full `OpenAPI` 3.1 spec
/// at runtime using `zodToJsonSchema` from the `zod-to-json-schema` package, giving
/// real component schemas instead of empty stubs.
pub fn emit_openapi_module(
    controller_files: &[ControllerFile],
    output_path: &Path,
    version: &str,
    title: &str,
    api_version: &str,
) -> Result<String, EmitError> {
    let out_dir = output_path.parent().unwrap_or_else(|| Path::new("."));
    let body = build_openapi_ts(controller_files, out_dir, title, api_version);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, &body, SourceType::ts()).parse();
    if !ret.errors.is_empty() {
        return Err(EmitError::EmittedSyntaxError {
            errors: ret.errors.iter().map(|e| format!("{e:?}")).collect(),
        });
    }
    let canonical = Codegen::new().build(&ret.program).code;

    let mut output = String::new();
    writeln!(
        output,
        "// AUTO-GENERATED by anvil-bellows v{version}. Do not edit."
    )
    .expect("write to String");
    output.push_str(&canonical);
    Ok(output)
}

/// Collect schema idents referenced via `$ref` in the `OpenAPI` spec — query params,
/// request bodies, and responses. Does NOT include `Params` schemas (path params
/// are always plain `type: "string"` in `OpenAPI`, not schema-typed).
fn collect_openapi_schema_idents(route: &Route, out: &mut BTreeSet<String>) {
    for param in &route.params {
        match &param.kind {
            ParamKind::Body(s)
            | ParamKind::Query(s)
            | ParamKind::FormBody(s)
            | ParamKind::Headers(s) => {
                out.insert(s.ident.clone());
            }
            ParamKind::Consumes { schema, .. } => {
                out.insert(schema.ident.clone());
            }
            _ => {}
        }
    }
    if let ReturnKind::Responds { schema, .. } = &route.return_kind {
        out.insert(schema.ident.clone());
    }
}

fn build_openapi_ts(
    files: &[ControllerFile],
    out_dir: &Path,
    title: &str,
    api_version: &str,
) -> String {
    let mut s = String::new();

    writeln!(
        s,
        "import {{ IntoSet, Module, Provides }} from \"@anvil-di/anvil\";"
    )
    .unwrap();
    writeln!(
        s,
        "import type {{ RouteDefinition }} from \"@anvil-di/bellows\";"
    )
    .unwrap();
    writeln!(
        s,
        "import {{ zodToJsonSchema }} from \"zod-to-json-schema\";"
    )
    .unwrap();

    let mut all_schemas: BTreeSet<String> = BTreeSet::new();
    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        let mut file_schemas: BTreeSet<String> = BTreeSet::new();
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                collect_openapi_schema_idents(route, &mut file_schemas);
            }
        }
        if !file_schemas.is_empty() {
            let names: Vec<&str> = file_schemas.iter().map(String::as_str).collect();
            writeln!(s, "import {{ {} }} from \"{specifier}\";", names.join(", ")).unwrap();
            all_schemas.extend(file_schemas);
        }
    }

    s.push('\n');

    writeln!(s, "@Module").unwrap();
    writeln!(s, "export class OpenApiModule {{").unwrap();
    writeln!(
        s,
        "  @IntoSet @Provides static openapiGetSpec(): RouteDefinition {{"
    )
    .unwrap();
    writeln!(s, "    return {{").unwrap();
    writeln!(s, "      method: \"GET\",").unwrap();
    writeln!(s, "      path: \"/openapi.json\",").unwrap();
    writeln!(
        s,
        "      handler: (_req, res) => {{ res.json(buildSpec()); }},"
    )
    .unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "}}").unwrap();
    s.push('\n');

    writeln!(s, "function buildSpec(): Record<string, unknown> {{").unwrap();
    writeln!(s, "  return {{").unwrap();
    writeln!(s, "    openapi: \"3.1.0\",").unwrap();
    writeln!(
        s,
        "    info: {{ title: \"{}\", version: \"{}\" }},",
        ts_escape(title),
        ts_escape(api_version)
    )
    .unwrap();
    openapi_emit_paths_ts(&mut s, files, "    ");
    if !all_schemas.is_empty() {
        writeln!(s, "    components: {{").unwrap();
        writeln!(s, "      schemas: {{").unwrap();
        for ident in &all_schemas {
            writeln!(
                s,
                "        {ident}: zodToJsonSchema({ident}, {{ $refStrategy: \"none\" }}),"
            )
            .unwrap();
        }
        writeln!(s, "      }},").unwrap();
        writeln!(s, "    }},").unwrap();
    }
    writeln!(s, "  }};").unwrap();
    writeln!(s, "}}").unwrap();

    if has_any_query_param(files) {
        s.push('\n');
        s.push_str(QUERY_PARAMETERS_HELPER);
    }

    s
}

/// Runtime helper that explodes a Zod-derived object JSON Schema into one
/// `OpenAPI` query parameter per property (issue #22). Emitted only when at least
/// one route declares a `Query<S>` param, so `noUnusedLocals` stays happy.
const QUERY_PARAMETERS_HELPER: &str = "\
function queryParameters(schema: unknown): Record<string, unknown>[] {
  const obj = (schema ?? {}) as { properties?: Record<string, unknown>; required?: string[] };
  const properties = obj.properties ?? {};
  const required = new Set(obj.required ?? []);
  return Object.keys(properties).map((name) => ({
    in: \"query\",
    name,
    required: required.has(name),
    schema: properties[name],
  }));
}
";

/// True if any route in any controller declares a `Query<S>` parameter.
fn has_any_query_param(files: &[ControllerFile]) -> bool {
    files.iter().any(|file| {
        file.controllers.iter().any(|ctrl| {
            ctrl.routes.iter().any(|route| {
                route
                    .params
                    .iter()
                    .any(|p| matches!(p.kind, ParamKind::Query(_)))
            })
        })
    })
}

type PathMap<'a> = BTreeMap<String, BTreeMap<String, (&'a Controller, &'a Route, Vec<String>)>>;

fn openapi_emit_paths_ts(s: &mut String, files: &[ControllerFile], indent: &str) {
    let mut path_map: PathMap<'_> = BTreeMap::new();
    for file in files {
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                let (openapi_path, path_params) = openapi_express_path(&route.path);
                let method_key = route.method.http_verb().to_lowercase();
                path_map
                    .entry(openapi_path)
                    .or_default()
                    .insert(method_key, (ctrl, route, path_params));
            }
        }
    }

    writeln!(s, "{indent}paths: {{").unwrap();
    for (path, methods) in &path_map {
        writeln!(s, "{indent}  \"{path}\": {{").unwrap();
        for (method, (ctrl, route, path_params)) in methods {
            openapi_emit_operation_ts(
                s,
                method,
                ctrl,
                route,
                path_params,
                &format!("{indent}    "),
            );
        }
        writeln!(s, "{indent}  }},").unwrap();
    }
    writeln!(s, "{indent}}},").unwrap();
}

#[allow(clippy::too_many_lines)]
fn openapi_emit_operation_ts(
    s: &mut String,
    method: &str,
    ctrl: &Controller,
    route: &Route,
    path_params: &[String],
    indent: &str,
) {
    writeln!(s, "{indent}{method}: {{").unwrap();

    let op_id = openapi_operation_id(&ctrl.class_name, &route.method, &route.handler_name);
    writeln!(s, "{indent}  operationId: \"{op_id}\",").unwrap();

    let tags: Vec<String> = if ctrl.tags.is_empty() {
        vec![format!("\"{}\"", openapi_default_tag(&ctrl.class_name))]
    } else {
        ctrl.tags
            .iter()
            .map(|t| format!("\"{}\"", ts_escape(t)))
            .collect()
    };
    writeln!(s, "{indent}  tags: [{}],", tags.join(", ")).unwrap();

    if route.deprecated {
        writeln!(s, "{indent}  deprecated: true,").unwrap();
    }

    let has_query = route
        .params
        .iter()
        .any(|p| matches!(p.kind, ParamKind::Query(_)));
    let has_headers = route
        .params
        .iter()
        .any(|p| matches!(p.kind, ParamKind::Headers(_)));
    if !path_params.is_empty() || has_query || has_headers {
        writeln!(s, "{indent}  parameters: [").unwrap();
        for pname in path_params {
            writeln!(
                s,
                "{indent}    {{ in: \"path\", name: \"{pname}\", required: true, schema: {{ type: \"string\" }} }},"
            )
            .unwrap();
        }
        for param in &route.params {
            if let ParamKind::Query(schema) = &param.kind {
                // Explode the object schema into one query parameter per
                // property at runtime. The Zod schema is the source of truth for
                // property names, per-property schemas, and `required` — data the
                // static IR doesn't carry — so we expand `zodToJsonSchema(...)`
                // via the `queryParameters` helper rather than emit a single
                // opaque `query` object param (issue #22).
                let schema_id = &schema.ident;
                writeln!(
                    s,
                    "{indent}    ...queryParameters(zodToJsonSchema({schema_id}, {{ $refStrategy: \"none\" }})),"
                )
                .unwrap();
            }
        }
        for param in &route.params {
            if let ParamKind::Headers(schema) = &param.kind {
                let schema_id = &schema.ident;
                let name = &param.name;
                writeln!(
                    s,
                    "{indent}    {{ in: \"header\", name: \"{name}\", required: false, schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }},"
                )
                .unwrap();
            }
        }
        writeln!(s, "{indent}  ],").unwrap();
    }

    if let Some(body_param) = route.params.iter().find(|p| {
        matches!(
            p.kind,
            ParamKind::Body(_) | ParamKind::FormBody(_) | ParamKind::Consumes { .. }
        )
    }) {
        let (schema_id, content_type): (&str, &str) = match &body_param.kind {
            ParamKind::Body(schema) => (&schema.ident, "application/json"),
            ParamKind::FormBody(schema) => (&schema.ident, "application/x-www-form-urlencoded"),
            ParamKind::Consumes { schema, codec } => (
                &schema.ident,
                codec
                    .content_type
                    .as_deref()
                    .unwrap_or("application/octet-stream"),
            ),
            _ => unreachable!("filtered above"),
        };
        writeln!(s, "{indent}  requestBody: {{").unwrap();
        writeln!(
            s,
            "{indent}    content: {{ \"{content_type}\": {{ schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }} }},"
        )
        .unwrap();
        writeln!(s, "{indent}    required: true,").unwrap();
        writeln!(s, "{indent}  }},").unwrap();
    }

    writeln!(s, "{indent}  responses: {{").unwrap();
    match &route.return_kind {
        ReturnKind::Responds { schema, codec, .. } => {
            let schema_id = &schema.ident;
            let content_type = codec
                .as_ref()
                .and_then(|c| c.content_type.as_deref())
                .unwrap_or("application/json");
            writeln!(
                s,
                "{indent}    \"200\": {{ content: {{ \"{content_type}\": {{ schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }} }}, description: \"Success\" }},"
            )
            .unwrap();
        }
        ReturnKind::Void { .. } => {
            writeln!(s, "{indent}    \"200\": {{ description: \"Success\" }},").unwrap();
        }
    }
    for er in &route.extra_responses {
        let code = er.status;
        let desc = openapi_status_desc(code);
        writeln!(s, "{indent}    \"{code}\": {{ description: \"{desc}\" }},").unwrap();
    }
    writeln!(s, "{indent}  }},").unwrap();
    writeln!(s, "{indent}}},").unwrap();
}

fn ts_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn openapi_express_path(path: &str) -> (String, Vec<String>) {
    let mut params = Vec::new();
    let segments: Vec<String> = path
        .split('/')
        .map(|seg| {
            if let Some(name) = seg.strip_prefix(':') {
                params.push(name.to_owned());
                format!("{{{name}}}")
            } else {
                seg.to_owned()
            }
        })
        .collect();
    (segments.join("/"), params)
}

fn openapi_operation_id(class_name: &str, method: &HttpMethod, handler: &str) -> String {
    format!(
        "{}{}{}",
        lower_first(class_name),
        method.decorator_name(),
        upper_first(handler)
    )
}

fn openapi_default_tag(class_name: &str) -> String {
    class_name
        .strip_suffix("Controller")
        .unwrap_or(class_name)
        .to_lowercase()
}

fn openapi_status_desc(status: u16) -> &'static str {
    match status {
        200 => "Success",
        201 => "Created",
        204 => "No Content",
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        422 => "Unprocessable Entity",
        500 => "Internal Server Error",
        _ => "Response",
    }
}

/// Collect schema identifiers from a route's params and return kind into `out`.
fn collect_schema_refs(route: &Route, out: &mut Vec<String>) {
    let mut push = |ident: &str| {
        if !out.contains(&ident.to_owned()) {
            out.push(ident.to_owned());
        }
    };
    for param in &route.params {
        match &param.kind {
            ParamKind::Body(s)
            | ParamKind::Query(s)
            | ParamKind::Params(s)
            | ParamKind::FormBody(s)
            | ParamKind::Headers(s) => push(&s.ident),
            ParamKind::Consumes { schema, codec } => {
                push(&schema.ident);
                push(&codec.ident);
            }
            _ => {}
        }
    }
    if let ReturnKind::Responds { schema, codec, .. } = &route.return_kind {
        push(&schema.ident);
        if let Some(codec) = codec {
            push(&codec.ident);
        }
    }
}

/// Returns true when all params are recognized types (no `Unknown`).
fn all_params_recognized(route: &Route) -> bool {
    route
        .params
        .iter()
        .all(|p| !matches!(p.kind, ParamKind::Unknown))
}

/// Which body parser `bellowsRoutes` should mount for a route.
#[derive(Debug, PartialEq, Eq)]
enum BodyParserKind<'a> {
    /// One of the three built-in kinds (`RouteDefinition.bodyParser`'s string variants).
    Named(&'static str),
    /// The two-arg `Body<S, C>` — mount a per-route codec-driven parser
    /// scoped to `C.contentType`. Carries the codec's identifier; codegen
    /// reads `{ident}.contentType`/`{ident}.decode` as runtime JS expressions
    /// rather than needing the content type resolved statically here.
    Codec(&'a str),
}

/// Determine which body parser `bellowsRoutes` should mount for this route,
/// derived from its params: the two-arg `Body<S, C>` takes priority and
/// mounts a codec-driven parser scoped to `C`'s content type; otherwise
/// `FormBody<S>` needs `urlencoded`, `Body<S>` needs `json`, a bare `RawBody`
/// with none of those needs `raw`, and a route with none of them needs no
/// body parsing at all.
fn route_body_parser(route: &Route) -> Option<BodyParserKind<'_>> {
    let mut has_body = false;
    let mut has_form = false;
    let mut has_raw = false;
    let mut codec_ident: Option<&str> = None;
    for param in &route.params {
        match &param.kind {
            ParamKind::Body(_) => has_body = true,
            ParamKind::FormBody(_) => has_form = true,
            ParamKind::RawBody => has_raw = true,
            ParamKind::Consumes { codec, .. } => codec_ident = Some(codec.ident.as_str()),
            _ => {}
        }
    }
    if let Some(ident) = codec_ident {
        Some(BodyParserKind::Codec(ident))
    } else if has_form {
        Some(BodyParserKind::Named("urlencoded"))
    } else if has_body {
        Some(BodyParserKind::Named("json"))
    } else if has_raw {
        Some(BodyParserKind::Named("raw"))
    } else {
        None
    }
}

/// Emit the handler expression for a route.
///
/// - All Unknown params → v0.1 passthrough: `(req, res) => ctrl.method(req, res)`
/// - All recognized params → typed adapter with validation
fn emit_handler(ctrl_param: &str, handler: &str, route: &Route) -> String {
    // If no params at all, or any param is Unknown, use v0.1 passthrough.
    if route.params.is_empty() || !all_params_recognized(route) {
        return format!("(req, res) => {ctrl_param}.{handler}(req, res)");
    }

    let is_async = matches!(
        route.return_kind,
        ReturnKind::Responds { is_async: true, .. } | ReturnKind::Void { is_async: true }
    );
    let async_kw = if is_async { "async " } else { "" };

    let mut body = String::new();

    // Schema validation prologue — one block per schema param.
    let mut call_args: Vec<String> = Vec::new();
    for param in &route.params {
        let schema_source = match &param.kind {
            // The two-arg `Body<S, C>`'s `bodyParser: { kind: "codec", ... }`
            // mount already replaced `req.body` with the codec's decoded
            // value before the handler runs, so it validates the same way.
            ParamKind::Body(schema)
            | ParamKind::FormBody(schema)
            | ParamKind::Consumes { schema, .. } => Some((schema, "req.body")),
            ParamKind::Query(schema) => Some((schema, "req.query")),
            ParamKind::Params(schema) => Some((schema, "req.params")),
            ParamKind::Headers(schema) => Some((schema, "req.headers")),
            _ => None,
        };
        if let Some((schema, source)) = schema_source {
            let s = &schema.ident;
            let n = &param.name;
            writeln!(body, "      const _{n} = {s}.safeParse({source});").unwrap();
            writeln!(
                body,
                "      if (!_{n}.success) {{ throw new BadRequestError(_{n}.error.message); }}"
            )
            .unwrap();
            call_args.push(format!("_{n}.data"));
            continue;
        }
        match &param.kind {
            ParamKind::RawBody => call_args.push("req.rawBody".to_owned()),
            ParamKind::Request => call_args.push("req".to_owned()),
            ParamKind::Response => call_args.push("res".to_owned()),
            // Express types `Response.locals` as `Record<string, any>`, so
            // this is assignable to `T` in `AuthnUser<T>` without a cast.
            ParamKind::User(_) => call_args.push("res.locals.user".to_owned()),
            ParamKind::Sse => {
                call_args.push("new SseStream(res, disconnectSignal(req))".to_owned());
            }
            ParamKind::Signal => call_args.push("disconnectSignal(req)".to_owned()),
            ParamKind::Unknown => unreachable!("filtered above"),
            ParamKind::Body(_)
            | ParamKind::FormBody(_)
            | ParamKind::Query(_)
            | ParamKind::Params(_)
            | ParamKind::Headers(_)
            | ParamKind::Consumes { .. } => unreachable!("handled above"),
        }
    }

    let args = call_args.join(", ");
    let await_kw = if is_async { "await " } else { "" };

    match &route.return_kind {
        ReturnKind::Responds { schema, codec, .. } => {
            let s = &schema.ident;
            writeln!(
                body,
                "      const _result = {await_kw}{ctrl_param}.{handler}({args});"
            )
            .unwrap();
            writeln!(body, "      const _validated = {s}.safeParse(_result);").unwrap();
            writeln!(body, "      if (!_validated.success) {{ throw new InternalServerError(_validated.error.message); }}").unwrap();
            if let Some(codec) = codec {
                let c = &codec.ident;
                write!(
                    body,
                    "      res.type({c}.contentType).send({c}.encode(_validated.data));"
                )
                .unwrap();
            } else {
                body.push_str("      res.json(_validated.data);");
            }
        }
        ReturnKind::Void { .. } => {
            // Controller manages `res` itself.
            write!(body, "      {await_kw}{ctrl_param}.{handler}({args});").unwrap();
        }
    }

    // Trim trailing newline from body so oxc_codegen formats cleanly.
    let body = body.trim_end();

    format!("{async_kw}(req, res) => {{\n{body}\n    }}")
}

/// Generate the provider static method name from controller class, decorator, and handler.
///
/// `UserController` + `Get` + `byId` → `userControllerGetById`
fn provider_method_name(class_name: &str, decorator: &str, handler: &str) -> String {
    format!(
        "{}{}{}",
        lower_first(class_name),
        decorator,
        upper_first(handler)
    )
}

/// Lower-case the first character of a string.
fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().to_string() + chars.as_str(),
    }
}

/// Upper-case the first character of a string.
fn upper_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

/// Compute a `./`-prefixed relative import specifier from `out_dir` to `source_path`,
/// stripping the `.ts` extension.
fn import_specifier(out_dir: &Path, source_path: &Path) -> String {
    let without_ext = strip_ts_extension(source_path);
    let rel = relative_path(out_dir, &without_ext).unwrap_or_else(|| without_ext.clone());
    let raw = rel.to_string_lossy().replace('\\', "/");
    if raw.starts_with("./") || raw.starts_with("../") {
        raw
    } else {
        format!("./{raw}")
    }
}

/// Strip `.ts`, `.tsx`, or `.d.ts` from a path.
fn strip_ts_extension(path: &Path) -> PathBuf {
    let s = path.to_string_lossy();
    for suffix in [".d.ts", ".tsx", ".ts"] {
        if let Some(stripped) = s.strip_suffix(suffix) {
            return PathBuf::from(stripped);
        }
    }
    path.to_path_buf()
}

/// Compute a relative path from `from` (a directory) to `to` (a file path),
/// both expected to be absolute or consistently relative.
fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from_comps: Vec<Component<'_>> = from.components().collect();
    let to_comps: Vec<Component<'_>> = to.components().collect();
    let mut i = 0;
    while i < from_comps.len() && i < to_comps.len() && from_comps[i] == to_comps[i] {
        i += 1;
    }
    let mut rel = PathBuf::new();
    for _ in &from_comps[i..] {
        rel.push("..");
    }
    for comp in &to_comps[i..] {
        rel.push(comp);
    }
    if rel.as_os_str().is_empty() {
        None
    } else {
        Some(rel)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{Controller, HttpMethod, ReturnKind, Route, TypedParam};

    fn make_file(path: &str, class: &str, routes: Vec<(&str, HttpMethod, &str)>) -> ControllerFile {
        ControllerFile {
            source_path: PathBuf::from(path),
            controllers: vec![Controller {
                class_name: class.to_owned(),
                ctor_params: vec![],
                tags: vec![],
                security: vec![],
                routes: routes
                    .into_iter()
                    .map(|(p, m, h)| Route {
                        method: m,
                        path: p.to_owned(),
                        handler_name: h.to_owned(),
                        is_sse: false,
                        params: vec![],
                        return_kind: ReturnKind::Void { is_async: false },
                        deprecated: false,
                        extra_responses: vec![],
                        middleware: vec![],
                        authn: vec![],
                        authz: vec![],
                    })
                    .collect(),
            }],
        }
    }

    fn make_typed_file(
        path: &str,
        class: &str,
        routes: Vec<(&str, HttpMethod, &str, Vec<TypedParam>, ReturnKind)>,
    ) -> ControllerFile {
        ControllerFile {
            source_path: PathBuf::from(path),
            controllers: vec![Controller {
                class_name: class.to_owned(),
                ctor_params: vec![],
                tags: vec![],
                security: vec![],
                routes: routes
                    .into_iter()
                    .map(|(p, m, h, params, return_kind)| Route {
                        method: m,
                        path: p.to_owned(),
                        handler_name: h.to_owned(),
                        is_sse: false,
                        params,
                        return_kind,
                        deprecated: false,
                        extra_responses: vec![],
                        middleware: vec![],
                        authn: vec![],
                        authz: vec![],
                    })
                    .collect(),
            }],
        }
    }

    #[test]
    fn provider_method_name_cases() {
        assert_eq!(
            provider_method_name("UserController", "Get", "byId"),
            "userControllerGetById"
        );
        assert_eq!(
            provider_method_name("PostController", "Post", "create"),
            "postControllerPostCreate"
        );
        assert_eq!(
            provider_method_name("HealthController", "Get", "ping"),
            "healthControllerGetPing"
        );
    }

    #[test]
    fn emit_single_controller() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![
                ("/users/:id", HttpMethod::Get, "byId"),
                ("/users", HttpMethod::Post, "create"),
            ],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("@Module"));
        assert!(result.contains("RoutesModule"));
        assert!(result.contains("userControllerGetById"));
        assert!(result.contains("userControllerPostCreate"));
        assert!(result.contains("\"GET\""));
        assert!(result.contains("\"/users/:id\""));
        assert!(result.contains("import { UserController }"));
        assert!(result.contains("\"./user-controller\""));
    }

    #[test]
    fn emit_multiple_controllers() {
        let files = vec![
            make_file(
                "/project/src/post-controller.ts",
                "PostController",
                vec![("/posts", HttpMethod::Get, "list")],
            ),
            make_file(
                "/project/src/user-controller.ts",
                "UserController",
                vec![("/users", HttpMethod::Get, "list")],
            ),
        ];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("PostController"));
        assert!(result.contains("UserController"));
        assert!(result.contains("postControllerGetList"));
        assert!(result.contains("userControllerGetList"));
    }

    #[test]
    fn emit_typed_adapter_body_and_responds() {
        use crate::parser::{ParamKind, SchemaRef};

        let params = vec![
            TypedParam {
                name: "body".into(),
                kind: ParamKind::Body(SchemaRef {
                    ident: "CreateBody".into(),
                }),
            },
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Request,
            },
        ];
        let return_kind = ReturnKind::Responds {
            schema: SchemaRef {
                ident: "UserSchema".into(),
            },
            codec: None,
            is_async: false,
        };

        let files = vec![make_typed_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users", HttpMethod::Post, "create", params, return_kind)],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // Schema imports alongside the controller.
        assert!(result.contains("UserController, CreateBody, UserSchema"));
        // safeParse calls.
        assert!(result.contains("CreateBody.safeParse(req.body)"));
        assert!(result.contains("UserSchema.safeParse(_result)"));
        // Errors are thrown, not responded to directly, so the shared
        // errorHandler middleware maps them.
        assert!(result.contains("throw new BadRequestError(_body.error.message)"));
        assert!(result.contains("throw new InternalServerError(_validated.error.message)"));
        assert!(result.contains(
            "import { BadRequestError, InternalServerError } from \"@anvil-di/bellows\""
        ));
        // Success response.
        assert!(result.contains("res.json(_validated.data)"));
        // No typeof in generated code.
        assert!(!result.contains("typeof CreateBody"));
    }

    #[test]
    fn emit_typed_adapter_produces_uses_codec_instead_of_json() {
        use crate::parser::{CodecRef, ParamKind, SchemaRef};

        let params = vec![TypedParam {
            name: "body".into(),
            kind: ParamKind::Body(SchemaRef {
                ident: "GatherWebhookSchema".into(),
            }),
        }];
        let return_kind = ReturnKind::Responds {
            schema: SchemaRef {
                ident: "TwimlResponseSchema".into(),
            },
            codec: Some(CodecRef {
                ident: "twimlCodec".into(),
                content_type: Some("application/xml".into()),
            }),
            is_async: true,
        };

        let files = vec![make_typed_file(
            "/project/src/webhooks-controller.ts",
            "WebhooksController",
            vec![(
                "/webhooks/gather",
                HttpMethod::Post,
                "gather",
                params,
                return_kind,
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // Codec import alongside the controller and schema.
        assert!(result
            .contains("WebhooksController, GatherWebhookSchema, TwimlResponseSchema, twimlCodec"));
        // Validates against the schema, then hands off to the codec — no res.json().
        assert!(result.contains("TwimlResponseSchema.safeParse(_result)"));
        assert!(result
            .contains("res.type(twimlCodec.contentType).send(twimlCodec.encode(_validated.data))"));
        assert!(!result.contains("res.json(_validated.data)"));
    }

    #[test]
    fn emit_typed_adapter_form_body_headers_raw_body() {
        use crate::parser::{ParamKind, SchemaRef};

        let params = vec![
            TypedParam {
                name: "body".into(),
                kind: ParamKind::FormBody(SchemaRef {
                    ident: "GatherBody".into(),
                }),
            },
            TypedParam {
                name: "headers".into(),
                kind: ParamKind::Headers(SchemaRef {
                    ident: "SignatureHeaders".into(),
                }),
            },
            TypedParam {
                name: "raw".into(),
                kind: ParamKind::RawBody,
            },
        ];
        let return_kind = ReturnKind::Void { is_async: false };

        let files = vec![make_typed_file(
            "/project/src/webhooks-controller.ts",
            "WebhooksController",
            vec![(
                "/webhooks/gather",
                HttpMethod::Post,
                "gather",
                params,
                return_kind,
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // Route requests the urlencoded body parser (FormBody wins over a bare RawBody).
        assert!(result.contains("bodyParser: \"urlencoded\""));
        assert!(result.contains("GatherBody.safeParse(req.body)"));
        assert!(result.contains("SignatureHeaders.safeParse(req.headers)"));
        assert!(result.contains("req.rawBody"));
    }

    #[test]
    fn route_body_parser_selects_json_urlencoded_raw_or_none() {
        use crate::parser::{CodecRef, ParamKind, SchemaRef};

        let route_with = |kinds: Vec<ParamKind>| Route {
            method: HttpMethod::Post,
            path: "/x".into(),
            handler_name: "h".into(),
            is_sse: false,
            params: kinds
                .into_iter()
                .enumerate()
                .map(|(i, kind)| TypedParam {
                    name: format!("p{i}"),
                    kind,
                })
                .collect(),
            return_kind: ReturnKind::Void { is_async: false },
            deprecated: false,
            extra_responses: vec![],
            middleware: vec![],
            authn: vec![],
            authz: vec![],
        };

        assert_eq!(
            route_body_parser(&route_with(vec![ParamKind::Body(SchemaRef {
                ident: "S".into()
            })])),
            Some(BodyParserKind::Named("json"))
        );
        assert_eq!(
            route_body_parser(&route_with(vec![ParamKind::FormBody(SchemaRef {
                ident: "S".into()
            })])),
            Some(BodyParserKind::Named("urlencoded"))
        );
        assert_eq!(
            route_body_parser(&route_with(vec![ParamKind::RawBody])),
            Some(BodyParserKind::Named("raw"))
        );
        assert_eq!(
            route_body_parser(&route_with(vec![
                ParamKind::FormBody(SchemaRef { ident: "S".into() }),
                ParamKind::RawBody
            ])),
            Some(BodyParserKind::Named("urlencoded"))
        );
        assert_eq!(
            route_body_parser(&route_with(vec![ParamKind::Request])),
            None
        );
        assert_eq!(
            route_body_parser(&route_with(vec![ParamKind::Consumes {
                schema: SchemaRef { ident: "S".into() },
                codec: CodecRef {
                    ident: "myCodec".into(),
                    content_type: Some("application/xml".into())
                }
            }])),
            Some(BodyParserKind::Codec("myCodec"))
        );
        assert_eq!(
            route_body_parser(&route_with(vec![
                ParamKind::Consumes {
                    schema: SchemaRef { ident: "S".into() },
                    codec: CodecRef {
                        ident: "myCodec".into(),
                        content_type: Some("application/xml".into())
                    }
                },
                ParamKind::RawBody
            ])),
            Some(BodyParserKind::Codec("myCodec"))
        );
    }

    #[test]
    fn emit_authn_user_param_injects_res_locals_user() {
        use crate::parser::{ParamKind, UserTypeRef};

        let params = vec![
            TypedParam {
                name: "user".into(),
                kind: ParamKind::User(UserTypeRef {
                    type_name: "AdminUser".into(),
                    identity: None,
                }),
            },
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Request,
            },
        ];

        let files = vec![make_typed_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![(
                "/admin/stats",
                HttpMethod::Get,
                "stats",
                params,
                ReturnKind::Void { is_async: false },
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        assert!(result.contains("adminController.stats(res.locals.user, req)"));
    }

    #[test]
    fn unknown_params_fallback_to_passthrough() {
        use crate::parser::ParamKind;

        let params = vec![
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Unknown,
            },
            TypedParam {
                name: "res".into(),
                kind: ParamKind::Unknown,
            },
        ];
        let files = vec![make_typed_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![(
                "/users",
                HttpMethod::Get,
                "list",
                params,
                ReturnKind::Void { is_async: false },
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // v0.1 passthrough shape.
        assert!(result.contains("(req, res) => userController.list(req, res)"));
        // No safeParse.
        assert!(!result.contains("safeParse"));
    }

    #[test]
    fn no_middleware_field_when_empty() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users/:id", HttpMethod::Get, "byId")],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(!result.contains("middleware"));
    }

    #[test]
    fn emits_middleware_array_and_imports() {
        use crate::parser::{ImportOrigin, MiddlewareRef};

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin", HttpMethod::Get, "dashboard")],
        );
        file.controllers[0].routes[0].middleware = vec![
            MiddlewareRef {
                name: "requireAuth".into(),
                origin: Some(ImportOrigin::Relative(PathBuf::from(
                    "/project/src/auth-middleware.ts",
                ))),
            },
            MiddlewareRef {
                name: "auditLog".into(),
                origin: None,
            },
            MiddlewareRef {
                name: "rateLimit".into(),
                origin: Some(ImportOrigin::Package("express-rate-limit".into())),
            },
        ];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        assert!(result.contains("import { requireAuth } from \"./auth-middleware\";"));
        assert!(result.contains("import { rateLimit } from \"express-rate-limit\";"));
        // `auditLog` has no resolvable origin — assumed declared in the controller file.
        assert!(
            result.contains("import { AdminController, auditLog } from \"./admin-controller\";")
        );
        assert!(result.contains("requireAuth"));
        assert!(result.contains("auditLog"));
        assert!(result.contains("rateLimit"));
        assert!(result.contains("middleware"));
    }

    #[test]
    fn no_authn_authz_fields_when_empty() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users/:id", HttpMethod::Get, "byId")],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(!result.contains("authn"));
        assert!(!result.contains("authz"));
    }

    #[test]
    fn emits_authn_authz_di_params_fields_and_imports() {
        use crate::parser::AuthRef;

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin/stats", HttpMethod::Get, "stats")],
        );
        file.controllers[0].routes[0].authn = vec![AuthRef {
            name: "SessionAuthn".into(),
            origin: Some(ImportOrigin::Relative(PathBuf::from(
                "/project/src/session-authn.ts",
            ))),
            scheme: Some("bearerAuth".into()),
            user_identity: None,
        }];
        file.controllers[0].routes[0].authz = vec![AuthRef {
            name: "RoleAuthz".into(),
            origin: None,
            scheme: None,
            user_identity: None,
        }];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        // Cross-file authn class gets a type-only import.
        assert!(result.contains("import type { SessionAuthn } from \"./session-authn\";"));
        // Same-file authz class is folded into the controller's value import.
        assert!(
            result.contains("import { AdminController, RoleAuthz } from \"./admin-controller\";")
        );
        // Extra DI params on the provider method.
        assert!(result.contains("sessionAuthn: SessionAuthn"));
        assert!(result.contains("roleAuthz: RoleAuthz"));
        // Fields on the RouteDefinition literal.
        assert!(result.contains("authn: [sessionAuthn]"));
        assert!(result.contains("authz: [roleAuthz]"));
    }

    #[test]
    fn authn_authz_referencing_same_class_share_one_di_param() {
        use crate::parser::AuthRef;

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin/stats", HttpMethod::Get, "stats")],
        );
        let shared = AuthRef {
            name: "AllInOne".into(),
            origin: None,
            scheme: None,
            user_identity: None,
        };
        file.controllers[0].routes[0].authn = vec![shared.clone()];
        file.controllers[0].routes[0].authz = vec![shared];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        // Only one `allInOne: AllInOne` parameter should appear, reused by both fields.
        assert_eq!(result.matches("allInOne: AllInOne").count(), 1);
        assert!(result.contains("authn: [allInOne]"));
        assert!(result.contains("authz: [allInOne]"));
    }
}
