//! Emit `routes.module.anvil.ts` and `schema-route.module.anvil.ts` from parsed
//! controller metadata.
//!
//! Follows the same strategy as `anvil-codegen`: build the TypeScript source as
//! a [`String`], validate it by parsing with Oxc, then re-emit with
//! `oxc_codegen::Codegen` for canonical formatting. The banner is prepended as
//! raw text (Codegen strips comments).

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Component, Path, PathBuf};

use oxc_allocator::Allocator;
use oxc_codegen::Codegen;
use oxc_parser::Parser;
use oxc_span::SourceType;
use thiserror::Error;

use crate::parser::{
    AuthRef, Controller, ControllerFile, CtorParam, HttpMethod, ImportOrigin, ParamKind,
    ReturnKind, Route,
};

/// Banner prepended to every generated file.
pub const BANNER: &str = "// AUTO-GENERATED by anvil-bellows. Do not edit.\n";

/// All ways code emission can fail.
#[derive(Debug, Error)]
pub enum EmitError {
    /// The string-built TS failed to parse — this is a codegen bug.
    #[error("emitter produced unparseable TypeScript: {errors:?}")]
    EmittedSyntaxError {
        /// Oxc parser error messages.
        errors: Vec<String>,
    },
}

/// Emit a `routes.module.ts` file.
///
/// `output_path` is where the file will be written; it is used to compute
/// relative import specifiers. `controller_files` is the parsed metadata from
/// [`crate::parser::parse_entry`].
///
/// # Errors
///
/// Returns [`EmitError`] if the generated TypeScript fails Oxc's parser (a
/// codegen invariant — should never happen with valid input).
pub fn emit_routes_module(
    controller_files: &[ControllerFile],
    output_path: &Path,
    version: &str,
) -> Result<String, EmitError> {
    let out_dir = output_path.parent().unwrap_or_else(|| Path::new("."));

    let body = build_ts(controller_files, out_dir);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, &body, SourceType::ts()).parse();
    if !ret.errors.is_empty() {
        return Err(EmitError::EmittedSyntaxError {
            errors: ret.errors.iter().map(|e| format!("{e:?}")).collect(),
        });
    }
    let canonical = Codegen::new().build(&ret.program).code;

    let mut output = String::new();
    writeln!(
        output,
        "// AUTO-GENERATED by anvil-bellows v{version}. Do not edit."
    )
    .expect("write to String");
    output.push_str(&canonical);
    Ok(output)
}

/// Build the raw TypeScript source string (before oxc canonicalization).
#[allow(clippy::too_many_lines, clippy::similar_names)]
fn build_ts(files: &[ControllerFile], out_dir: &Path) -> String {
    let mut s = String::new();

    let any_ctor_params = files
        .iter()
        .flat_map(|f| &f.controllers)
        .any(|c| !c.ctor_params.is_empty());
    let anvil_imports = if any_ctor_params {
        "Module, Provides, Singleton, IntoSet"
    } else {
        "Module, Provides, IntoSet"
    };
    writeln!(s, "import {{ {anvil_imports} }} from \"@anvil-di/anvil\";").unwrap();
    s.push_str("import type { RouteDefinition } from \"@anvil-di/bellows\";\n");

    // One import per controller file — includes controller class + any schema refs.
    // Also collect dep types that need separate imports.
    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        // Collect all identifiers to import from this file.
        let mut imports: Vec<String> = Vec::new();
        for ctrl in &file.controllers {
            imports.push(ctrl.class_name.clone());
            for route in &ctrl.routes {
                collect_schema_refs(route, &mut imports);
                for mw in &route.middleware {
                    if mw.origin.is_none() && !imports.contains(&mw.name) {
                        imports.push(mw.name.clone());
                    }
                }
                for a in route.authn.iter().chain(&route.authz) {
                    if a.origin.is_none() && !imports.contains(&a.name) {
                        imports.push(a.name.clone());
                    }
                }
            }
        }
        imports.dedup();
        writeln!(
            s,
            "import {{ {} }} from \"{specifier}\";",
            imports.join(", ")
        )
        .unwrap();
    }

    // Emit imports for controller dep types that come from other files.
    // Group by resolved absolute source path so we emit one import per file.
    let mut dep_imports: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for cp in &ctrl.ctor_params {
                let Some(abs) = &cp.abs_source else { continue };
                let spec = import_specifier(out_dir, abs);
                // Skip if the dep type is already imported from the controller file.
                if spec == ctrl_spec {
                    continue;
                }
                dep_imports
                    .entry(spec)
                    .or_default()
                    .push(cp.type_name.clone());
            }
        }
    }
    for (spec, mut names) in dep_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import type {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    // Emit imports for middleware functions that aren't declared in the
    // controller's own file — grouped by resolved specifier (relative file or
    // bare package), one import per specifier.
    let mut middleware_imports: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                for mw in &route.middleware {
                    let spec = match &mw.origin {
                        Some(ImportOrigin::Relative(abs)) => import_specifier(out_dir, abs),
                        Some(ImportOrigin::Package(pkg)) => pkg.clone(),
                        None => continue, // declared in the controller file — handled above
                    };
                    if spec == ctrl_spec {
                        continue;
                    }
                    middleware_imports
                        .entry(spec)
                        .or_default()
                        .push(mw.name.clone());
                }
            }
        }
    }
    for (spec, mut names) in middleware_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    // Emit type-only imports for @Authn/@Authz service classes that aren't
    // declared in the controller's own file — these are only ever used in a
    // type-annotation position on the generated provider method, never
    // called as a value, so `import type` is always correct here (unlike
    // middleware, which is imported as a value).
    let mut auth_imports: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for file in files {
        let ctrl_spec = import_specifier(out_dir, &file.source_path);
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                for a in route.authn.iter().chain(&route.authz) {
                    let spec = match &a.origin {
                        Some(ImportOrigin::Relative(abs)) => import_specifier(out_dir, abs),
                        Some(ImportOrigin::Package(pkg)) => pkg.clone(),
                        None => continue, // declared in the controller file — handled above
                    };
                    if spec == ctrl_spec {
                        continue;
                    }
                    auth_imports.entry(spec).or_default().push(a.name.clone());
                }
            }
        }
    }
    for (spec, mut names) in auth_imports {
        names.sort();
        names.dedup();
        writeln!(s, "import type {{ {} }} from \"{spec}\";", names.join(", ")).unwrap();
    }

    s.push('\n');
    s.push_str("@Module\n");
    s.push_str("export class RoutesModule {\n");

    for file in files {
        for ctrl in &file.controllers {
            // Emit a @Singleton @Provides binding for the controller itself,
            // taking its constructor deps as DI parameters.
            if !ctrl.ctor_params.is_empty() {
                emit_controller_provider(&mut s, ctrl.class_name.as_str(), &ctrl.ctor_params);
            }

            for route in &ctrl.routes {
                let method_name = provider_method_name(
                    &ctrl.class_name,
                    route.method.decorator_name(),
                    &route.handler_name,
                );
                let param_name = lower_first(&ctrl.class_name);
                let class_name = &ctrl.class_name;
                let http_verb = route.method.http_verb();
                let path = &route.path;

                let handler_body = emit_handler(&param_name, &route.handler_name, route);
                let middleware_field = if route.middleware.is_empty() {
                    String::new()
                } else {
                    let names: Vec<&str> =
                        route.middleware.iter().map(|m| m.name.as_str()).collect();
                    format!("\n      middleware: [{}],", names.join(", "))
                };
                let authn_field = auth_field("authn", &route.authn);
                let authz_field = auth_field("authz", &route.authz);
                let extra_params_sig = extra_auth_params_sig(route);

                writeln!(
                    s,
                    "  @IntoSet @Provides\n  static {method_name}({param_name}: {class_name}{extra_params_sig}): RouteDefinition {{\n    return {{\n      method: \"{http_verb}\",\n      path: \"{path}\",{middleware_field}{authn_field}{authz_field}\n      handler: {handler_body},\n    }};\n  }}"
                )
                .unwrap();
            }
        }
    }

    s.push_str("}\n");
    s
}

/// Render the `authn: [...]`/`authz: [...]` `RouteDefinition` field, or an
/// empty string when `refs` is empty (field omitted entirely).
fn auth_field(field_name: &str, refs: &[AuthRef]) -> String {
    if refs.is_empty() {
        return String::new();
    }
    let names: Vec<String> = refs.iter().map(|a| lower_first(&a.name)).collect();
    format!("\n      {field_name}: [{}],", names.join(", "))
}

/// Build the extra `, local: ClassName` DI parameters a route's provider
/// method needs for its `@Authn`/`@Authz` service classes, deduped by class
/// name (a class referenced by both decorators gets one shared parameter).
fn extra_auth_params_sig(route: &Route) -> String {
    let mut seen: Vec<&str> = Vec::new();
    let mut sig = String::new();
    for a in route.authn.iter().chain(&route.authz) {
        if seen.contains(&a.name.as_str()) {
            continue;
        }
        seen.push(&a.name);
        write!(sig, ", {}: {}", lower_first(&a.name), a.name).unwrap();
    }
    sig
}

/// Emit a `@Singleton @Provides` method that constructs a controller from its deps.
fn emit_controller_provider(s: &mut String, class_name: &str, ctor_params: &[CtorParam]) {
    let method_name = lower_first(class_name);
    let params_sig = ctor_params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.type_name))
        .collect::<Vec<_>>()
        .join(", ");
    let ctor_args = ctor_params
        .iter()
        .map(|p| p.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        s,
        "  @Singleton @Provides\n  static {method_name}({params_sig}): {class_name} {{\n    return new {class_name}({ctor_args});\n  }}"
    )
    .unwrap();
}

/// Emit a `schema-route.module.anvil.ts` alongside `routes.module.anvil.ts`.
///
/// The generated module exports `OpenApiModule` — an `@Module` class with a single
/// `@IntoSet @Provides` method that provides a `GET /openapi.json` route whose
/// handler calls `buildSpec()`. `buildSpec()` constructs the full `OpenAPI` 3.1 spec
/// at runtime using `zodToJsonSchema` from the `zod-to-json-schema` package, giving
/// real component schemas instead of empty stubs.
pub fn emit_openapi_module(
    controller_files: &[ControllerFile],
    output_path: &Path,
    version: &str,
    title: &str,
    api_version: &str,
) -> Result<String, EmitError> {
    let out_dir = output_path.parent().unwrap_or_else(|| Path::new("."));
    let body = build_openapi_ts(controller_files, out_dir, title, api_version);

    let allocator = Allocator::default();
    let ret = Parser::new(&allocator, &body, SourceType::ts()).parse();
    if !ret.errors.is_empty() {
        return Err(EmitError::EmittedSyntaxError {
            errors: ret.errors.iter().map(|e| format!("{e:?}")).collect(),
        });
    }
    let canonical = Codegen::new().build(&ret.program).code;

    let mut output = String::new();
    writeln!(
        output,
        "// AUTO-GENERATED by anvil-bellows v{version}. Do not edit."
    )
    .expect("write to String");
    output.push_str(&canonical);
    Ok(output)
}

/// Collect schema idents referenced via `$ref` in the `OpenAPI` spec — query params,
/// request bodies, and responses. Does NOT include `Params` schemas (path params
/// are always plain `type: "string"` in `OpenAPI`, not schema-typed).
fn collect_openapi_schema_idents(route: &Route, out: &mut BTreeSet<String>) {
    for param in &route.params {
        match &param.kind {
            ParamKind::Body(s) | ParamKind::Query(s) => {
                out.insert(s.ident.clone());
            }
            _ => {}
        }
    }
    if let ReturnKind::Responds { schema, .. } = &route.return_kind {
        out.insert(schema.ident.clone());
    }
}

fn build_openapi_ts(
    files: &[ControllerFile],
    out_dir: &Path,
    title: &str,
    api_version: &str,
) -> String {
    let mut s = String::new();

    writeln!(
        s,
        "import {{ IntoSet, Module, Provides }} from \"@anvil-di/anvil\";"
    )
    .unwrap();
    writeln!(
        s,
        "import type {{ RouteDefinition }} from \"@anvil-di/bellows\";"
    )
    .unwrap();
    writeln!(
        s,
        "import {{ zodToJsonSchema }} from \"zod-to-json-schema\";"
    )
    .unwrap();

    let mut all_schemas: BTreeSet<String> = BTreeSet::new();
    for file in files {
        let specifier = import_specifier(out_dir, &file.source_path);
        let mut file_schemas: BTreeSet<String> = BTreeSet::new();
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                collect_openapi_schema_idents(route, &mut file_schemas);
            }
        }
        if !file_schemas.is_empty() {
            let names: Vec<&str> = file_schemas.iter().map(String::as_str).collect();
            writeln!(s, "import {{ {} }} from \"{specifier}\";", names.join(", ")).unwrap();
            all_schemas.extend(file_schemas);
        }
    }

    s.push('\n');

    writeln!(s, "@Module").unwrap();
    writeln!(s, "export class OpenApiModule {{").unwrap();
    writeln!(
        s,
        "  @IntoSet @Provides static openapiGetSpec(): RouteDefinition {{"
    )
    .unwrap();
    writeln!(s, "    return {{").unwrap();
    writeln!(s, "      method: \"GET\",").unwrap();
    writeln!(s, "      path: \"/openapi.json\",").unwrap();
    writeln!(
        s,
        "      handler: (_req, res) => {{ res.json(buildSpec()); }},"
    )
    .unwrap();
    writeln!(s, "    }};").unwrap();
    writeln!(s, "  }}").unwrap();
    writeln!(s, "}}").unwrap();
    s.push('\n');

    writeln!(s, "function buildSpec(): Record<string, unknown> {{").unwrap();
    writeln!(s, "  return {{").unwrap();
    writeln!(s, "    openapi: \"3.1.0\",").unwrap();
    writeln!(
        s,
        "    info: {{ title: \"{}\", version: \"{}\" }},",
        ts_escape(title),
        ts_escape(api_version)
    )
    .unwrap();
    openapi_emit_paths_ts(&mut s, files, "    ");
    if !all_schemas.is_empty() {
        writeln!(s, "    components: {{").unwrap();
        writeln!(s, "      schemas: {{").unwrap();
        for ident in &all_schemas {
            writeln!(
                s,
                "        {ident}: zodToJsonSchema({ident}, {{ $refStrategy: \"none\" }}),"
            )
            .unwrap();
        }
        writeln!(s, "      }},").unwrap();
        writeln!(s, "    }},").unwrap();
    }
    writeln!(s, "  }};").unwrap();
    writeln!(s, "}}").unwrap();

    s
}

type PathMap<'a> = BTreeMap<String, BTreeMap<String, (&'a Controller, &'a Route, Vec<String>)>>;

fn openapi_emit_paths_ts(s: &mut String, files: &[ControllerFile], indent: &str) {
    let mut path_map: PathMap<'_> = BTreeMap::new();
    for file in files {
        for ctrl in &file.controllers {
            for route in &ctrl.routes {
                let (openapi_path, path_params) = openapi_express_path(&route.path);
                let method_key = route.method.http_verb().to_lowercase();
                path_map
                    .entry(openapi_path)
                    .or_default()
                    .insert(method_key, (ctrl, route, path_params));
            }
        }
    }

    writeln!(s, "{indent}paths: {{").unwrap();
    for (path, methods) in &path_map {
        writeln!(s, "{indent}  \"{path}\": {{").unwrap();
        for (method, (ctrl, route, path_params)) in methods {
            openapi_emit_operation_ts(
                s,
                method,
                ctrl,
                route,
                path_params,
                &format!("{indent}    "),
            );
        }
        writeln!(s, "{indent}  }},").unwrap();
    }
    writeln!(s, "{indent}}},").unwrap();
}

fn openapi_emit_operation_ts(
    s: &mut String,
    method: &str,
    ctrl: &Controller,
    route: &Route,
    path_params: &[String],
    indent: &str,
) {
    writeln!(s, "{indent}{method}: {{").unwrap();

    let op_id = openapi_operation_id(&ctrl.class_name, &route.method, &route.handler_name);
    writeln!(s, "{indent}  operationId: \"{op_id}\",").unwrap();

    let tags: Vec<String> = if ctrl.tags.is_empty() {
        vec![format!("\"{}\"", openapi_default_tag(&ctrl.class_name))]
    } else {
        ctrl.tags
            .iter()
            .map(|t| format!("\"{}\"", ts_escape(t)))
            .collect()
    };
    writeln!(s, "{indent}  tags: [{}],", tags.join(", ")).unwrap();

    if route.deprecated {
        writeln!(s, "{indent}  deprecated: true,").unwrap();
    }

    let has_query = route
        .params
        .iter()
        .any(|p| matches!(p.kind, ParamKind::Query(_)));
    if !path_params.is_empty() || has_query {
        writeln!(s, "{indent}  parameters: [").unwrap();
        for pname in path_params {
            writeln!(
                s,
                "{indent}    {{ in: \"path\", name: \"{pname}\", required: true, schema: {{ type: \"string\" }} }},"
            )
            .unwrap();
        }
        for param in &route.params {
            if let ParamKind::Query(schema) = &param.kind {
                let schema_id = &schema.ident;
                let name = &param.name;
                writeln!(
                    s,
                    "{indent}    {{ in: \"query\", name: \"{name}\", required: false, schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }},"
                )
                .unwrap();
            }
        }
        writeln!(s, "{indent}  ],").unwrap();
    }

    if let Some(body_param) = route
        .params
        .iter()
        .find(|p| matches!(p.kind, ParamKind::Body(_)))
    {
        if let ParamKind::Body(schema) = &body_param.kind {
            let schema_id = &schema.ident;
            writeln!(s, "{indent}  requestBody: {{").unwrap();
            writeln!(
                s,
                "{indent}    content: {{ \"application/json\": {{ schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }} }},"
            )
            .unwrap();
            writeln!(s, "{indent}    required: true,").unwrap();
            writeln!(s, "{indent}  }},").unwrap();
        }
    }

    writeln!(s, "{indent}  responses: {{").unwrap();
    match &route.return_kind {
        ReturnKind::Responds { schema, .. } => {
            let schema_id = &schema.ident;
            writeln!(
                s,
                "{indent}    \"200\": {{ content: {{ \"application/json\": {{ schema: {{ \"$ref\": \"#/components/schemas/{schema_id}\" }} }} }}, description: \"Success\" }},"
            )
            .unwrap();
        }
        ReturnKind::Void { .. } => {
            writeln!(s, "{indent}    \"200\": {{ description: \"Success\" }},").unwrap();
        }
    }
    for er in &route.extra_responses {
        let code = er.status;
        let desc = openapi_status_desc(code);
        writeln!(s, "{indent}    \"{code}\": {{ description: \"{desc}\" }},").unwrap();
    }
    writeln!(s, "{indent}  }},").unwrap();
    writeln!(s, "{indent}}},").unwrap();
}

fn ts_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn openapi_express_path(path: &str) -> (String, Vec<String>) {
    let mut params = Vec::new();
    let segments: Vec<String> = path
        .split('/')
        .map(|seg| {
            if let Some(name) = seg.strip_prefix(':') {
                params.push(name.to_owned());
                format!("{{{name}}}")
            } else {
                seg.to_owned()
            }
        })
        .collect();
    (segments.join("/"), params)
}

fn openapi_operation_id(class_name: &str, method: &HttpMethod, handler: &str) -> String {
    format!(
        "{}{}{}",
        lower_first(class_name),
        method.decorator_name(),
        upper_first(handler)
    )
}

fn openapi_default_tag(class_name: &str) -> String {
    class_name
        .strip_suffix("Controller")
        .unwrap_or(class_name)
        .to_lowercase()
}

fn openapi_status_desc(status: u16) -> &'static str {
    match status {
        200 => "Success",
        201 => "Created",
        204 => "No Content",
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        422 => "Unprocessable Entity",
        500 => "Internal Server Error",
        _ => "Response",
    }
}

/// Collect schema identifiers from a route's params and return kind into `out`.
fn collect_schema_refs(route: &Route, out: &mut Vec<String>) {
    for param in &route.params {
        let ident = match &param.kind {
            ParamKind::Body(s) | ParamKind::Query(s) | ParamKind::Params(s) => &s.ident,
            _ => continue,
        };
        if !out.contains(ident) {
            out.push(ident.clone());
        }
    }
    if let ReturnKind::Responds { schema, codec, .. } = &route.return_kind {
        if !out.contains(&schema.ident) {
            out.push(schema.ident.clone());
        }
        if let Some(codec) = codec {
            if !out.contains(&codec.ident) {
                out.push(codec.ident.clone());
            }
        }
    }
}

/// Returns true when all params are recognized types (no `Unknown`).
fn all_params_recognized(route: &Route) -> bool {
    route
        .params
        .iter()
        .all(|p| !matches!(p.kind, ParamKind::Unknown))
}

/// Emit the handler expression for a route.
///
/// - All Unknown params → v0.1 passthrough: `(req, res) => ctrl.method(req, res)`
/// - All recognized params → typed adapter with validation
fn emit_handler(ctrl_param: &str, handler: &str, route: &Route) -> String {
    // If no params at all, or any param is Unknown, use v0.1 passthrough.
    if route.params.is_empty() || !all_params_recognized(route) {
        return format!("(req, res) => {ctrl_param}.{handler}(req, res)");
    }

    let is_async = matches!(
        route.return_kind,
        ReturnKind::Responds { is_async: true, .. } | ReturnKind::Void { is_async: true }
    );
    let async_kw = if is_async { "async " } else { "" };

    let mut body = String::new();

    // Schema validation prologue — one block per schema param.
    let mut call_args: Vec<String> = Vec::new();
    for param in &route.params {
        match &param.kind {
            ParamKind::Body(schema) => {
                let s = &schema.ident;
                let n = &param.name;
                writeln!(body, "      const _{n} = {s}.safeParse(req.body);").unwrap();
                writeln!(
                    body,
                    "      if (!_{n}.success) {{ res.status(400).json(_{n}.error); return; }}"
                )
                .unwrap();
                call_args.push(format!("_{n}.data"));
            }
            ParamKind::Query(schema) => {
                let s = &schema.ident;
                let n = &param.name;
                writeln!(body, "      const _{n} = {s}.safeParse(req.query);").unwrap();
                writeln!(
                    body,
                    "      if (!_{n}.success) {{ res.status(400).json(_{n}.error); return; }}"
                )
                .unwrap();
                call_args.push(format!("_{n}.data"));
            }
            ParamKind::Params(schema) => {
                let s = &schema.ident;
                let n = &param.name;
                writeln!(body, "      const _{n} = {s}.safeParse(req.params);").unwrap();
                writeln!(
                    body,
                    "      if (!_{n}.success) {{ res.status(400).json(_{n}.error); return; }}"
                )
                .unwrap();
                call_args.push(format!("_{n}.data"));
            }
            ParamKind::Request => call_args.push("req".to_owned()),
            ParamKind::Response => call_args.push("res".to_owned()),
            // Express types `Response.locals` as `Record<string, any>`, so
            // this is assignable to `T` in `AuthnUser<T>` without a cast.
            ParamKind::User(_) => call_args.push("res.locals.user".to_owned()),
            ParamKind::Unknown => unreachable!("filtered above"),
        }
    }

    let args = call_args.join(", ");
    let await_kw = if is_async { "await " } else { "" };

    match &route.return_kind {
        ReturnKind::Responds { schema, codec, .. } => {
            let s = &schema.ident;
            writeln!(
                body,
                "      const _result = {await_kw}{ctrl_param}.{handler}({args});"
            )
            .unwrap();
            writeln!(body, "      const _validated = {s}.safeParse(_result);").unwrap();
            writeln!(body, "      if (!_validated.success) {{ res.status(500).json(_validated.error); return; }}").unwrap();
            if let Some(codec) = codec {
                let c = &codec.ident;
                write!(
                    body,
                    "      res.type({c}.contentType).send({c}.encode(_validated.data));"
                )
                .unwrap();
            } else {
                body.push_str("      res.json(_validated.data);");
            }
        }
        ReturnKind::Void { .. } => {
            // Controller manages `res` itself.
            write!(body, "      {await_kw}{ctrl_param}.{handler}({args});").unwrap();
        }
    }

    // Trim trailing newline from body so oxc_codegen formats cleanly.
    let body = body.trim_end();

    format!("{async_kw}(req, res) => {{\n{body}\n    }}")
}

/// Generate the provider static method name from controller class, decorator, and handler.
///
/// `UserController` + `Get` + `byId` → `userControllerGetById`
fn provider_method_name(class_name: &str, decorator: &str, handler: &str) -> String {
    format!(
        "{}{}{}",
        lower_first(class_name),
        decorator,
        upper_first(handler)
    )
}

/// Lower-case the first character of a string.
fn lower_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().to_string() + chars.as_str(),
    }
}

/// Upper-case the first character of a string.
fn upper_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}

/// Compute a `./`-prefixed relative import specifier from `out_dir` to `source_path`,
/// stripping the `.ts` extension.
fn import_specifier(out_dir: &Path, source_path: &Path) -> String {
    let without_ext = strip_ts_extension(source_path);
    let rel = relative_path(out_dir, &without_ext).unwrap_or_else(|| without_ext.clone());
    let raw = rel.to_string_lossy().replace('\\', "/");
    if raw.starts_with("./") || raw.starts_with("../") {
        raw
    } else {
        format!("./{raw}")
    }
}

/// Strip `.ts`, `.tsx`, or `.d.ts` from a path.
fn strip_ts_extension(path: &Path) -> PathBuf {
    let s = path.to_string_lossy();
    for suffix in [".d.ts", ".tsx", ".ts"] {
        if let Some(stripped) = s.strip_suffix(suffix) {
            return PathBuf::from(stripped);
        }
    }
    path.to_path_buf()
}

/// Compute a relative path from `from` (a directory) to `to` (a file path),
/// both expected to be absolute or consistently relative.
fn relative_path(from: &Path, to: &Path) -> Option<PathBuf> {
    let from_comps: Vec<Component<'_>> = from.components().collect();
    let to_comps: Vec<Component<'_>> = to.components().collect();
    let mut i = 0;
    while i < from_comps.len() && i < to_comps.len() && from_comps[i] == to_comps[i] {
        i += 1;
    }
    let mut rel = PathBuf::new();
    for _ in &from_comps[i..] {
        rel.push("..");
    }
    for comp in &to_comps[i..] {
        rel.push(comp);
    }
    if rel.as_os_str().is_empty() {
        None
    } else {
        Some(rel)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{Controller, HttpMethod, ReturnKind, Route, TypedParam};

    fn make_file(path: &str, class: &str, routes: Vec<(&str, HttpMethod, &str)>) -> ControllerFile {
        ControllerFile {
            source_path: PathBuf::from(path),
            controllers: vec![Controller {
                class_name: class.to_owned(),
                ctor_params: vec![],
                tags: vec![],
                security: vec![],
                routes: routes
                    .into_iter()
                    .map(|(p, m, h)| Route {
                        method: m,
                        path: p.to_owned(),
                        handler_name: h.to_owned(),
                        params: vec![],
                        return_kind: ReturnKind::Void { is_async: false },
                        deprecated: false,
                        extra_responses: vec![],
                        middleware: vec![],
                        authn: vec![],
                        authz: vec![],
                    })
                    .collect(),
            }],
        }
    }

    fn make_typed_file(
        path: &str,
        class: &str,
        routes: Vec<(&str, HttpMethod, &str, Vec<TypedParam>, ReturnKind)>,
    ) -> ControllerFile {
        ControllerFile {
            source_path: PathBuf::from(path),
            controllers: vec![Controller {
                class_name: class.to_owned(),
                ctor_params: vec![],
                tags: vec![],
                security: vec![],
                routes: routes
                    .into_iter()
                    .map(|(p, m, h, params, return_kind)| Route {
                        method: m,
                        path: p.to_owned(),
                        handler_name: h.to_owned(),
                        params,
                        return_kind,
                        deprecated: false,
                        extra_responses: vec![],
                        middleware: vec![],
                        authn: vec![],
                        authz: vec![],
                    })
                    .collect(),
            }],
        }
    }

    #[test]
    fn provider_method_name_cases() {
        assert_eq!(
            provider_method_name("UserController", "Get", "byId"),
            "userControllerGetById"
        );
        assert_eq!(
            provider_method_name("PostController", "Post", "create"),
            "postControllerPostCreate"
        );
        assert_eq!(
            provider_method_name("HealthController", "Get", "ping"),
            "healthControllerGetPing"
        );
    }

    #[test]
    fn emit_single_controller() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![
                ("/users/:id", HttpMethod::Get, "byId"),
                ("/users", HttpMethod::Post, "create"),
            ],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("@Module"));
        assert!(result.contains("RoutesModule"));
        assert!(result.contains("userControllerGetById"));
        assert!(result.contains("userControllerPostCreate"));
        assert!(result.contains("\"GET\""));
        assert!(result.contains("\"/users/:id\""));
        assert!(result.contains("import { UserController }"));
        assert!(result.contains("\"./user-controller\""));
    }

    #[test]
    fn emit_multiple_controllers() {
        let files = vec![
            make_file(
                "/project/src/post-controller.ts",
                "PostController",
                vec![("/posts", HttpMethod::Get, "list")],
            ),
            make_file(
                "/project/src/user-controller.ts",
                "UserController",
                vec![("/users", HttpMethod::Get, "list")],
            ),
        ];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(result.contains("PostController"));
        assert!(result.contains("UserController"));
        assert!(result.contains("postControllerGetList"));
        assert!(result.contains("userControllerGetList"));
    }

    #[test]
    fn emit_typed_adapter_body_and_responds() {
        use crate::parser::{ParamKind, SchemaRef};

        let params = vec![
            TypedParam {
                name: "body".into(),
                kind: ParamKind::Body(SchemaRef {
                    ident: "CreateBody".into(),
                }),
            },
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Request,
            },
        ];
        let return_kind = ReturnKind::Responds {
            schema: SchemaRef {
                ident: "UserSchema".into(),
            },
            codec: None,
            is_async: false,
        };

        let files = vec![make_typed_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users", HttpMethod::Post, "create", params, return_kind)],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // Schema imports alongside the controller.
        assert!(result.contains("UserController, CreateBody, UserSchema"));
        // safeParse calls.
        assert!(result.contains("CreateBody.safeParse(req.body)"));
        assert!(result.contains("UserSchema.safeParse(_result)"));
        // Error responses.
        assert!(result.contains("res.status(400)"));
        assert!(result.contains("res.status(500)"));
        // Success response.
        assert!(result.contains("res.json(_validated.data)"));
        // No typeof in generated code.
        assert!(!result.contains("typeof CreateBody"));
    }

    #[test]
    fn emit_typed_adapter_produces_uses_codec_instead_of_json() {
        use crate::parser::{ParamKind, SchemaRef};

        let params = vec![TypedParam {
            name: "body".into(),
            kind: ParamKind::Body(SchemaRef {
                ident: "GatherWebhookSchema".into(),
            }),
        }];
        let return_kind = ReturnKind::Responds {
            schema: SchemaRef {
                ident: "TwimlResponseSchema".into(),
            },
            codec: Some(SchemaRef {
                ident: "twimlCodec".into(),
            }),
            is_async: true,
        };

        let files = vec![make_typed_file(
            "/project/src/webhooks-controller.ts",
            "WebhooksController",
            vec![(
                "/webhooks/gather",
                HttpMethod::Post,
                "gather",
                params,
                return_kind,
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // Codec import alongside the controller and schema.
        assert!(result
            .contains("WebhooksController, GatherWebhookSchema, TwimlResponseSchema, twimlCodec"));
        // Validates against the schema, then hands off to the codec — no res.json().
        assert!(result.contains("TwimlResponseSchema.safeParse(_result)"));
        assert!(result
            .contains("res.type(twimlCodec.contentType).send(twimlCodec.encode(_validated.data))"));
        assert!(!result.contains("res.json(_validated.data)"));
    }

    #[test]
    fn emit_authn_user_param_injects_res_locals_user() {
        use crate::parser::{ParamKind, UserTypeRef};

        let params = vec![
            TypedParam {
                name: "user".into(),
                kind: ParamKind::User(UserTypeRef {
                    type_name: "AdminUser".into(),
                    identity: None,
                }),
            },
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Request,
            },
        ];

        let files = vec![make_typed_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![(
                "/admin/stats",
                HttpMethod::Get,
                "stats",
                params,
                ReturnKind::Void { is_async: false },
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        assert!(result.contains("adminController.stats(res.locals.user, req)"));
    }

    #[test]
    fn unknown_params_fallback_to_passthrough() {
        use crate::parser::ParamKind;

        let params = vec![
            TypedParam {
                name: "req".into(),
                kind: ParamKind::Unknown,
            },
            TypedParam {
                name: "res".into(),
                kind: ParamKind::Unknown,
            },
        ];
        let files = vec![make_typed_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![(
                "/users",
                HttpMethod::Get,
                "list",
                params,
                ReturnKind::Void { is_async: false },
            )],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();

        // v0.1 passthrough shape.
        assert!(result.contains("(req, res) => userController.list(req, res)"));
        // No safeParse.
        assert!(!result.contains("safeParse"));
    }

    #[test]
    fn no_middleware_field_when_empty() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users/:id", HttpMethod::Get, "byId")],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(!result.contains("middleware"));
    }

    #[test]
    fn emits_middleware_array_and_imports() {
        use crate::parser::{ImportOrigin, MiddlewareRef};

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin", HttpMethod::Get, "dashboard")],
        );
        file.controllers[0].routes[0].middleware = vec![
            MiddlewareRef {
                name: "requireAuth".into(),
                origin: Some(ImportOrigin::Relative(PathBuf::from(
                    "/project/src/auth-middleware.ts",
                ))),
            },
            MiddlewareRef {
                name: "auditLog".into(),
                origin: None,
            },
            MiddlewareRef {
                name: "rateLimit".into(),
                origin: Some(ImportOrigin::Package("express-rate-limit".into())),
            },
        ];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        assert!(result.contains("import { requireAuth } from \"./auth-middleware\";"));
        assert!(result.contains("import { rateLimit } from \"express-rate-limit\";"));
        // `auditLog` has no resolvable origin — assumed declared in the controller file.
        assert!(
            result.contains("import { AdminController, auditLog } from \"./admin-controller\";")
        );
        assert!(result.contains("requireAuth"));
        assert!(result.contains("auditLog"));
        assert!(result.contains("rateLimit"));
        assert!(result.contains("middleware"));
    }

    #[test]
    fn no_authn_authz_fields_when_empty() {
        let files = vec![make_file(
            "/project/src/user-controller.ts",
            "UserController",
            vec![("/users/:id", HttpMethod::Get, "byId")],
        )];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&files, output_path, "0.0.1").unwrap();
        assert!(!result.contains("authn"));
        assert!(!result.contains("authz"));
    }

    #[test]
    fn emits_authn_authz_di_params_fields_and_imports() {
        use crate::parser::AuthRef;

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin/stats", HttpMethod::Get, "stats")],
        );
        file.controllers[0].routes[0].authn = vec![AuthRef {
            name: "SessionAuthn".into(),
            origin: Some(ImportOrigin::Relative(PathBuf::from(
                "/project/src/session-authn.ts",
            ))),
            scheme: Some("bearerAuth".into()),
            user_identity: None,
        }];
        file.controllers[0].routes[0].authz = vec![AuthRef {
            name: "RoleAuthz".into(),
            origin: None,
            scheme: None,
            user_identity: None,
        }];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        // Cross-file authn class gets a type-only import.
        assert!(result.contains("import type { SessionAuthn } from \"./session-authn\";"));
        // Same-file authz class is folded into the controller's value import.
        assert!(
            result.contains("import { AdminController, RoleAuthz } from \"./admin-controller\";")
        );
        // Extra DI params on the provider method.
        assert!(result.contains("sessionAuthn: SessionAuthn"));
        assert!(result.contains("roleAuthz: RoleAuthz"));
        // Fields on the RouteDefinition literal.
        assert!(result.contains("authn: [sessionAuthn]"));
        assert!(result.contains("authz: [roleAuthz]"));
    }

    #[test]
    fn authn_authz_referencing_same_class_share_one_di_param() {
        use crate::parser::AuthRef;

        let mut file = make_file(
            "/project/src/admin-controller.ts",
            "AdminController",
            vec![("/admin/stats", HttpMethod::Get, "stats")],
        );
        let shared = AuthRef {
            name: "AllInOne".into(),
            origin: None,
            scheme: None,
            user_identity: None,
        };
        file.controllers[0].routes[0].authn = vec![shared.clone()];
        file.controllers[0].routes[0].authz = vec![shared];
        let output_path = Path::new("/project/src/routes.module.ts");
        let result = emit_routes_module(&[file], output_path, "0.0.1").unwrap();

        // Only one `allInOne: AllInOne` parameter should appear, reused by both fields.
        assert_eq!(result.matches("allInOne: AllInOne").count(), 1);
        assert!(result.contains("authn: [allInOne]"));
        assert!(result.contains("authz: [allInOne]"));
    }
}
