// AUTO-GENERATED by tsdi v0.0.1. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import { Heater } from "./heater";
import { RequestComponent } from "./request-component";
import { RequestHandler } from "./request-handler";
export class DaggerAppComponent extends AppComponent {
	private _heater: Heater | undefined;
	getHeater(): Heater {
		return this._heater ??= new Heater();
	}
	heater(): Heater {
		return this.getHeater();
	}
	requestComponent(): RequestComponent {
		return new DaggerRequestComponent(this);
	}
	static create(): AppComponent {
		return new DaggerAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return DaggerAppComponent.create();
}
export class DaggerRequestComponent extends RequestComponent {
	constructor(private parent: DaggerAppComponent) {
		super();
	}
	private getRequestHandler(): RequestHandler {
		return new RequestHandler(this.parent.getHeater());
	}
	handler(): RequestHandler {
		return this.getRequestHandler();
	}
}
