// AUTO-GENERATED by anvil v0.0.1. Do not edit.
// Source: ./app-component.ts
import { AppComponent } from "./app-component";
import { ConsoleLogger } from "./console-logger";
import type { Logger } from "./logger";
import { UserRepository } from "./user-repository";
import { UserService } from "./user-service";
export class AnvilAppComponent extends AppComponent {
	private _consoleLogger: ConsoleLogger | undefined;
	private _userRepository: UserRepository | undefined;
	private getConsoleLogger(): ConsoleLogger {
		return this._consoleLogger ??= new ConsoleLogger();
	}
	private getLogger(): Logger {
		return this.getConsoleLogger();
	}
	private getUserRepository(): UserRepository {
		return this._userRepository ??= new UserRepository();
	}
	private getUserService(): UserService {
		return new UserService(this.getUserRepository(), this.getLogger());
	}
	logger(): Logger {
		return this.getLogger();
	}
	userService(): UserService {
		return this.getUserService();
	}
	static create(): AppComponent {
		return new AnvilAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return AnvilAppComponent.create();
}
