//! TypeScript code emitter for the tsdi DI framework.
//!
//! M4 lands the first real emitter for `@Component` + `@Module` +
//! `@Provides` + `@Inject` ctors at `Scope::Unscoped`. Singleton
//! caching arrives in M6.
//!
//! # Strategy
//!
//! Per `docs/adr/0004-per-component-output-file.md` we emit one
//! `<component>.tsdi.ts` per `@Component`, co-located with source.
//!
//! The emitter builds the generated TypeScript as a [`String`], then
//! pipes it through [`oxc_parser`] (structural-correctness gate — a
//! parse failure here means the emitter has a bug, never the user) and
//! [`oxc_codegen`] (canonical formatting). The banner is prepended to
//! that canonicalized output as a leading comment.
//!
//! See `docs/codegen.md` for the input→output worked example and the
//! naming/ordering conventions.

mod emit_component;

pub use emit_component::emit_component;

use thiserror::Error;
use tsdi_core::validate::Diagnostic;

/// Banner prepended to every generated file. Kept stable so users can `grep` for it.
///
/// The trailing newline is intentional: it separates the banner from the
/// source-comment line that follows it.
pub const BANNER_PREFIX: &str = "// AUTO-GENERATED by tsdi";

/// All ways code emission can fail.
#[derive(Debug, Error)]
pub enum EmitError {
    /// Validation produced one or more diagnostics; the graph is unsafe to emit.
    #[error("graph failed validation ({} diagnostic(s))", .0.len())]
    Invalid(Vec<Diagnostic>),
    /// The graph contains a [`tsdi_core::ir::Scope::Singleton`] binding.
    /// Singleton emission lands in M6.
    #[error("singleton scope is not yet supported (binding `{key_name}`); lands in M6")]
    SingletonNotYetSupported {
        /// The class name of the offending binding.
        key_name: String,
    },
    /// The component's source path has no parent directory. Should not
    /// happen post-M2; guarded for safety.
    #[error("component source path has no parent directory: {0}")]
    BadComponentPath(String),
    /// The string-built TS failed to parse. This is an emitter bug.
    #[error("emitter produced unparseable TS: {errors:?}")]
    EmittedSyntaxError {
        /// Parser error messages.
        errors: Vec<String>,
    },
}

/// Result alias used across this module.
pub type Result<T> = std::result::Result<T, EmitError>;

/// Build the banner line for a generated file.
///
/// # Examples
///
/// ```
/// let banner = tsdi_codegen::banner_for("0.0.1");
/// assert!(banner.starts_with("// AUTO-GENERATED by tsdi"));
/// assert!(banner.contains("0.0.1"));
/// ```
#[must_use]
pub fn banner_for(version: &str) -> String {
    format!("{BANNER_PREFIX} v{version}. Do not edit.\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn banner_includes_version() {
        let b = banner_for("9.9.9");
        assert!(b.contains("9.9.9"));
        assert!(b.starts_with(BANNER_PREFIX));
    }
}
