// AUTO-GENERATED by anvil v0.0.1. Do not edit.
// Source: ./app-component.ts
import type { RouteDefinition } from "../../../../packages/anvil-bellows/dist/index.js";
import { AppComponent } from "./app-component";
import { RoutesModule } from "./routes.module";
import type { TodoController } from "./todo-controller";
import { TodoModule } from "./todo-module";
import type { TodoService } from "./todo-service";
export class DaggerAppComponent extends AppComponent {
	private _todoService: TodoService | undefined;
	private _todoController: TodoController | undefined;
	private getTodoService(): TodoService {
		return this._todoService ??= TodoModule.todoService();
	}
	private getTodoController(): TodoController {
		return this._todoController ??= RoutesModule.todoController(this.getTodoService());
	}
	private getSetOfRouteDefinition(): Set<RouteDefinition> {
		return new Set([
			RoutesModule.todoControllerGetList(this.getTodoController()),
			RoutesModule.todoControllerGetById(this.getTodoController()),
			RoutesModule.todoControllerPostCreate(this.getTodoController()),
			RoutesModule.todoControllerPutUpdate(this.getTodoController()),
			RoutesModule.todoControllerDeleteRemove(this.getTodoController())
		]);
	}
	routeDefinitions(): Set<RouteDefinition> {
		return this.getSetOfRouteDefinition();
	}
	static create(): AppComponent {
		return new DaggerAppComponent();
	}
}
export function createAppComponent(): AppComponent {
	return DaggerAppComponent.create();
}
