// AUTO-GENERATED by anvil-bellows v0.0.3. Do not edit.
import { Module, Provides, Singleton, IntoSet } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { TodoController, TodoQuery, TodoListSchema, TodoParams, TodoSchema, CreateTodoBody, UpdateTodoBody } from "./todo-controller";
import type { TodoService } from "./todo-service";
export @Module class RoutesModule {
	@Singleton @Provides static todoController(todoService: TodoService): TodoController {
		return new TodoController(todoService);
	}
	@IntoSet @Provides static todoControllerGetList(todoController: TodoController): RouteDefinition {
		return {
			method: "GET",
			path: "/todos",
			handler: (req, res) => {
				const _query = TodoQuery.safeParse(req.query);
				if (!_query.success) {
					res.status(400).json(_query.error);
					return;
				}
				const _result = todoController.list(_query.data);
				const _validated = TodoListSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static todoControllerGetById(todoController: TodoController): RouteDefinition {
		return {
			method: "GET",
			path: "/todos/:id",
			handler: (req, res) => {
				const _params = TodoParams.safeParse(req.params);
				if (!_params.success) {
					res.status(400).json(_params.error);
					return;
				}
				const _result = todoController.byId(_params.data);
				const _validated = TodoSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static todoControllerPostCreate(todoController: TodoController): RouteDefinition {
		return {
			method: "POST",
			path: "/todos",
			bodyParser: "json",
			handler: (req, res) => {
				const _body = CreateTodoBody.safeParse(req.body);
				if (!_body.success) {
					res.status(400).json(_body.error);
					return;
				}
				const _result = todoController.create(_body.data);
				const _validated = TodoSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static todoControllerPutUpdate(todoController: TodoController): RouteDefinition {
		return {
			method: "PUT",
			path: "/todos/:id",
			bodyParser: "json",
			handler: (req, res) => {
				const _params = TodoParams.safeParse(req.params);
				if (!_params.success) {
					res.status(400).json(_params.error);
					return;
				}
				const _body = UpdateTodoBody.safeParse(req.body);
				if (!_body.success) {
					res.status(400).json(_body.error);
					return;
				}
				const _result = todoController.update(_params.data, _body.data);
				const _validated = TodoSchema.safeParse(_result);
				if (!_validated.success) {
					res.status(500).json(_validated.error);
					return;
				}
				res.json(_validated.data);
			}
		};
	}
	@IntoSet @Provides static todoControllerDeleteRemove(todoController: TodoController): RouteDefinition {
		return {
			method: "DELETE",
			path: "/todos/:id",
			handler: (req, res) => {
				const _params = TodoParams.safeParse(req.params);
				if (!_params.success) {
					res.status(400).json(_params.error);
					return;
				}
				todoController.remove(_params.data, res);
			}
		};
	}
}
