// AUTO-GENERATED by anvil-bellows v0.0.4. Do not edit.
import { IntoSet, Module, Provides } from "@anvil-di/anvil";
import type { RouteDefinition } from "@anvil-di/bellows";
import { zodToJsonSchema } from "zod-to-json-schema";
import { CreateTodoBody, TodoListSchema, TodoQuery, TodoSchema, UpdateTodoBody } from "./todo-controller";
export @Module class OpenApiModule {
	@IntoSet @Provides static openapiGetSpec(): RouteDefinition {
		return {
			method: "GET",
			path: "/openapi.json",
			handler: (_req, res) => {
				res.json(buildSpec());
			}
		};
	}
}
function buildSpec(): Record<string, unknown> {
	return {
		openapi: "3.1.0",
		info: {
			title: "Todo API",
			version: "0.0.1"
		},
		paths: {
			"/todos": {
				get: {
					operationId: "todoControllerGetList",
					tags: ["todos"],
					parameters: [...queryParameters(zodToJsonSchema(TodoQuery, { $refStrategy: "none" }))],
					responses: { "200": {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/TodoListSchema" } } },
						description: "Success"
					} }
				},
				post: {
					operationId: "todoControllerPostCreate",
					tags: ["todos"],
					requestBody: {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/CreateTodoBody" } } },
						required: true
					},
					responses: { "200": {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/TodoSchema" } } },
						description: "Success"
					} }
				}
			},
			"/todos/{id}": {
				delete: {
					operationId: "todoControllerDeleteRemove",
					tags: ["todos"],
					parameters: [{
						in: "path",
						name: "id",
						required: true,
						schema: { type: "string" }
					}],
					responses: {
						"200": { description: "Success" },
						"204": { description: "No Content" }
					}
				},
				get: {
					operationId: "todoControllerGetById",
					tags: ["todos"],
					parameters: [{
						in: "path",
						name: "id",
						required: true,
						schema: { type: "string" }
					}],
					responses: { "200": {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/TodoSchema" } } },
						description: "Success"
					} }
				},
				put: {
					operationId: "todoControllerPutUpdate",
					tags: ["todos"],
					parameters: [{
						in: "path",
						name: "id",
						required: true,
						schema: { type: "string" }
					}],
					requestBody: {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/UpdateTodoBody" } } },
						required: true
					},
					responses: { "200": {
						content: { "application/json": { schema: { "$ref": "#/components/schemas/TodoSchema" } } },
						description: "Success"
					} }
				}
			}
		},
		components: { schemas: {
			CreateTodoBody: zodToJsonSchema(CreateTodoBody, { $refStrategy: "none" }),
			TodoListSchema: zodToJsonSchema(TodoListSchema, { $refStrategy: "none" }),
			TodoQuery: zodToJsonSchema(TodoQuery, { $refStrategy: "none" }),
			TodoSchema: zodToJsonSchema(TodoSchema, { $refStrategy: "none" }),
			UpdateTodoBody: zodToJsonSchema(UpdateTodoBody, { $refStrategy: "none" })
		} }
	};
}
function queryParameters(schema: unknown): Record<string, unknown>[] {
	const obj = (schema ?? {}) as {
		properties?: Record<string, unknown>;
		required?: string[];
	};
	const properties = obj.properties ?? {};
	const required = new Set(obj.required ?? []);
	return Object.keys(properties).map((name) => ({
		in: "query",
		name,
		required: required.has(name),
		schema: properties[name]
	}));
}
