// AUTO-GENERATED by anvil v0.0.1. Do not edit.
// Source: ./spec-component.ts
import type { RouteDefinition } from "../../../../packages/bellows/dist/index.js";
import { OpenApiModule } from "./schema-route.module.anvil";
import { SpecComponent } from "./spec-component";
export class AnvilSpecComponent extends SpecComponent {
	private getSetOfRouteDefinition(): Set<RouteDefinition> {
		return new Set([OpenApiModule.openapiGetSpec()]);
	}
	routeDefinitions(): Set<RouteDefinition> {
		return this.getSetOfRouteDefinition();
	}
	static create(): SpecComponent {
		return new AnvilSpecComponent();
	}
}
export function createSpecComponent(): SpecComponent {
	return AnvilSpecComponent.create();
}
